import { useMemo,useState } from 'react';
import { Button } from '../../../shared/ui/Button';
import { Dialog } from '../../../shared/ui/Dialog';
import { Feedback } from '../../../shared/ui/Feedback';
import { Input } from '../../../shared/ui/Input';
import { Select } from '../../../shared/ui/Select';
import type { EngineeringProductionSnapshot } from '../infrastructure/EngineeringProductionReadRepository';
import { createManualProductionService,saveEngineeringProductionPrice,type ProductionServiceKind } from '../infrastructure/EngineeringProductionPriceRepository';

interface Props{open:boolean;scope:{tenantId:string;companyId:string};snapshot:EngineeringProductionSnapshot;onClose:()=>void;onSaved:()=>void;}
const cents=(digits:string)=>Number(digits||'0')/100;
const money=(digits:string)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents(digits));

export function EngineeringProductionPriceDialog({open,scope,snapshot,onClose,onSaved}:Props){
 const[type,setType]=useState<ProductionServiceKind>('linked');const[structureId,setStructureId]=useState('');const[serviceId,setServiceId]=useState('');const[name,setName]=useState('');const[unit,setUnit]=useState('APTO');const[valueDigits,setValueDigits]=useState('');const[plannedQuantity,setPlannedQuantity]=useState('');const[distribution,setDistribution]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
 const towers=snapshot.structureNodes.filter(s=>!s.parentId&&s.structureType==='tower');
 const structureOptions=[{value:'',label:type==='linked'?'Selecione…':'Selecione a torre…'},...towers.map(s=>({value:s.id,label:s.name}))];
 const children=structureId?snapshot.structureNodes.filter(s=>s.parentId===structureId):[];
 const distribute=()=>{const total=Number(plannedQuantity.replace(',','.'))||0;if(!children.length||total<=0)return;const discrete=['UN','UND','UNID','UNIDADE','APTO','APT','APARTAMENTO'].includes(unit.trim().toUpperCase());if(discrete&&Number.isInteger(total)){const whole=Math.floor(total/children.length);const remainder=total%children.length;setDistribution(Object.fromEntries(children.map((c,index)=>[c.id,String(whole+(index<remainder?1:0))])));return;}const base=total/children.length;setDistribution(Object.fromEntries(children.map((c,index)=>{const value=index===children.length-1?total-base*(children.length-1):base;return[c.id,String(Number(value.toFixed(3))).replace('.',',')];})));};
 const services=useMemo(()=>{const allowed=new Set(snapshot.serviceIdsByStructure[structureId]??[]);return snapshot.services.filter(s=>allowed.has(s.id));},[snapshot.services,snapshot.serviceIdsByStructure,structureId]);
 const serviceOptions=[{value:'',label:structureId?(services.length?'Selecione…':'Nenhum serviço nesta estrutura'):'Selecione a estrutura primeiro'},...services.map(s=>({value:s.id,label:`${s.name}${s.unit?` · ${s.unit}`:''}`}))];
 const existing=type==='linked'&&serviceId?snapshot.productionPrices.find(p=>p.structureId===structureId&&p.contractServiceId===serviceId):undefined;
 function changeType(next:ProductionServiceKind){setType(next);setStructureId('');setServiceId('');setName('');setUnit(next==='manual'?'APTO':'');setValueDigits('');setPlannedQuantity('');setDistribution({});setError(null);}
 function changeStructure(id:string){setStructureId(id);setServiceId('');setValueDigits('');setError(null);}
 function changeService(id:string){setServiceId(id);const found=snapshot.productionPrices.find(p=>p.structureId===structureId&&p.contractServiceId===id);setValueDigits(found?String(Math.round(found.unitValue*100)):'');setError(null);}
 async function submit(finalize=false){const unitValue=cents(valueDigits);if(type==='linked'&&(!structureId||!serviceId)){setError('Selecione a estrutura e o serviço.');return;}if(type!=='linked'&&!name.trim()){setError(type==='discount'?'Informe o nome do desconto.':'Informe o nome do serviço manual.');return;}if(unitValue<0){setError('Informe um valor válido.');return;}setBusy(true);setError(null);try{if(type==='linked')await saveEngineeringProductionPrice({...scope,workId:snapshot.workId,contractServiceId:serviceId,structureId,unitValue});else await createManualProductionService({...scope,workId:snapshot.workId,name,unit:unit||null,kind:type,structureId:structureId||null,unitValue,plannedQuantity:Number(plannedQuantity.replace(',','.'))||0,allocations:Object.entries(distribution).map(([structureId,quantity])=>({structureId,quantity:Number(quantity.replace(',','.'))||0}))});onSaved();setServiceId('');setName('');setUnit(type==='manual'?'APTO':'');setValueDigits('');setPlannedQuantity('');setDistribution({});if(finalize)onClose();}catch(c){setError(c instanceof Error?c.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 return <Dialog open={open} title="Cadastrar valores de produção" description="Use a mesma estrutura física da Engenharia e cadastre manualmente os serviços, quantidades e valores exclusivos da Produção." onClose={onClose} onBack={onClose} footer={<><Button type="button" variant="secondary" onClick={()=>void submit(false)} disabled={busy}>＋ Adicionar serviço</Button><Button type="button" onClick={()=>void submit(true)} loading={busy}>{existing?'Atualizar e finalizar':'Salvar e finalizar'}</Button></>} loading={busy}>
  <div className="engineering-production-entry-form">
   {error&&<Feedback tone="danger" title="Não foi possível salvar" message={error}/>}
   <div className="engineering-production-entry-form__grid">
    <Select label="Tipo" value={type} onChange={e=>changeType(e.target.value as ProductionServiceKind)} options={[{value:'linked',label:'Serviço do contrato'},{value:'manual',label:'Serviço manual'},{value:'discount',label:'Desconto'}]}/>
    <Select label={type==='linked'?'Torre / Estrutura':'Torre / Estrutura (opcional)'} value={structureId} onChange={e=>changeStructure(e.target.value)} options={structureOptions} required={type==='linked'}/>
    {type==='linked'?<Select label="Serviço" value={serviceId} onChange={e=>changeService(e.target.value)} options={serviceOptions} disabled={!structureId||services.length===0} required/>:<Input label={type==='discount'?'Descrição do desconto':'Nome do serviço'} value={name} onChange={e=>setName(e.target.value)} required/>}
    {type==='manual'&&<><Input label="Unidade" value={unit} onChange={e=>setUnit(e.target.value)} placeholder="APTO, UN, M²..."/><Input label="Quantidade total" inputMode="decimal" value={plannedQuantity} onChange={e=>setPlannedQuantity(e.target.value.replace(/[^0-9,.]/g,''))}/></>}
    <Input label="Valor unitário de produção" inputMode="numeric" value={money(valueDigits)} onChange={e=>setValueDigits(e.target.value.replace(/\D/g,''))} required/>
   </div>
   {type==='manual'&&structureId&&children.length>0&&<section className="engineering-production-distribution"><div className="engineering-production-parity__section-head"><div><h3>Distribuir por pavimento</h3><span>{children.length} estrutura(s) dentro de {towers.find(t=>t.id===structureId)?.name}</span></div><Button type="button" size="sm" variant="secondary" onClick={distribute}>Dividir igualmente</Button></div><div className="engineering-production-entry-form__grid">{children.map(child=><Input key={child.id} label={child.name} inputMode="decimal" value={distribution[child.id]??''} onChange={e=>setDistribution(current=>({...current,[child.id]:e.target.value.replace(/[^0-9,.]/g,'')}))}/>)}</div></section>}
   {structureId&&<section><h3>Valores cadastrados nesta estrutura</h3>{snapshot.productionPrices.filter(p=>p.structureId===structureId).length===0?<p className="ui-muted">Nenhum valor de produção cadastrado.</p>:<div className="engineering-production-parity__table-wrap"><table className="engineering-production-parity__table"><thead><tr><th>Serviço</th><th>Tipo</th><th>Unidade</th><th>Quantidade</th><th>Valor unitário</th><th>Total</th><th></th></tr></thead><tbody>{snapshot.productionPrices.filter(p=>p.structureId===structureId).map((p,index)=>{const s=snapshot.services.find(x=>x.contractServiceId===p.contractServiceId);const serviceName=p.productionServiceName??s?.name??'Serviço';const qty=p.plannedQuantity??0;return <tr key={p.productionServiceId??p.contractServiceId??index}><td><strong>{serviceName}</strong></td><td>{p.productionServiceKind==='manual'?'Manual':p.productionServiceKind==='discount'?'Desconto':'Contrato'}</td><td>{p.unit??s?.unit??'—'}</td><td>{p.plannedQuantity==null?'—':new Intl.NumberFormat('pt-BR',{maximumFractionDigits:3}).format(qty)}</td><td>{new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(p.unitValue)}</td><td><strong>{p.plannedQuantity==null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(qty*p.unitValue)}</strong></td><td>{p.contractServiceId&&<Button size="sm" variant="tertiary" onClick={()=>changeService(p.contractServiceId!)}>Editar</Button>}</td></tr>})}</tbody></table></div>}</section>}
  </div>
 </Dialog>;
}
