import { useCallback, useEffect, useMemo, useState } from 'react';
import type { CompanySummary } from '../../platform/domain/AccessContext';
import type { EngineeringContractSummary } from '../domain/overview';
import { Button } from '../../../shared/ui/Button';
import { Card } from '../../../shared/ui/Card';
import { Input } from '../../../shared/ui/Input';
import { MoneyInput } from '../../../shared/ui/MoneyInput';
import { Select } from '../../../shared/ui/Select';
import { sharePrintableElement } from '../../../shared/utils/reportShare';
import { addServiceControlEntry, addServiceControlItem, deleteServiceControlItem, ensureServiceControl, listServiceControls, updateServiceControlItem, type ServiceControl, type ServiceControlItem } from '../infrastructure/EngineeringServiceControlRepository';
import './engineering-service-control.css';

const currency=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const qty=(v:number)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(v);
const monthNow=()=>new Date().toISOString().slice(0,7);
const today=()=>new Date().toISOString().slice(0,10);
const numberOf=(v:string)=>Number(v.replace(/\./g,'').replace(',','.'))||0;
interface Props{contracts:readonly EngineeringContractSummary[];companies:readonly CompanySummary[]}

export function EngineeringServiceControl({contracts,companies}:Props){
 const [selectedContractId,setSelectedContractId]=useState(''),[control,setControl]=useState<ServiceControl|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[month,setMonth]=useState(monthNow());
 const [serviceName,setServiceName]=useState(''),[unit,setUnit]=useState('m'),[totalValue,setTotalValue]=useState(0),[contractedQty,setContractedQty]=useState(''),[serviceNotes,setServiceNotes]=useState(''),[editing,setEditing]=useState<ServiceControlItem|null>(null),[pendingDelete,setPendingDelete]=useState<ServiceControlItem|null>(null);
 const [entryItem,setEntryItem]=useState(''),[date,setDate]=useState(today()),[quantity,setQuantity]=useState(''),[notes,setNotes]=useState('');
 const selectedContract=contracts.find(c=>c.contractId===selectedContractId)??null;
 const company=selectedContract?companies.find(c=>c.id===selectedContract.companyId)??null:null;
 const scope=useMemo(()=>company?{tenantId:company.tenantId,companyId:company.id}:null,[company]);
 const load=useCallback(async()=>{if(!scope||!selectedContract){setControl(null);return;}setLoading(true);setError('');try{const all=await listServiceControls(scope);setControl(all.find(x=>x.contractId===selectedContract.contractId)??null);}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar o controle.');}finally{setLoading(false);}},[scope,selectedContract]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(!scope||!selectedContract||control||loading)return;void ensureServiceControl(scope,selectedContract.contractId,selectedContract.workName+' · '+selectedContract.contractNumber).then(load).catch(e=>setError(e instanceof Error?e.message:'Falha ao criar controle.'));},[scope,selectedContract,control,loading,load]);
 const rows=useMemo(()=>control?.items.map(item=>{const entries=control.entries.filter(e=>e.itemId===item.id),acc=entries.reduce((s,e)=>s+e.executedQuantity,0),monthly=entries.filter(e=>e.executionDate.slice(0,7)===month).reduce((s,e)=>s+e.executedQuantity,0),remaining=Math.max(0,item.contractedQuantity-acc);return {...item,acc,monthly,remaining,monthlyValue:monthly*item.unitPrice,accValue:acc*item.unitPrice,remainingValue:remaining*item.unitPrice,percent:item.contractedQuantity>0?acc/item.contractedQuantity*100:0};})??[],[control,month]);
 const totals=rows.reduce((a,r)=>({contracted:a.contracted+r.contractedValue,monthly:a.monthly+r.monthlyValue,acc:a.acc+r.accValue,remaining:a.remaining+r.remainingValue}),{contracted:0,monthly:0,acc:0,remaining:0});
 const contractOptions=[{value:'',label:'Selecione o contrato / obra…'},...contracts.map(c=>({value:c.contractId,label:c.workName+' · '+c.contractNumber}))];
 const itemOptions=[{value:'',label:'Selecione o serviço…'},...rows.map(r=>({value:r.id,label:r.description+' · saldo '+qty(r.remaining)+' '+r.unit}))];
 const calculatedUnit=numberOf(contractedQty)>0?totalValue/numberOf(contractedQty):0;
 function resetService(){setServiceName('');setUnit('m');setTotalValue(0);setContractedQty('');setServiceNotes('');setEditing(null);}
 function editService(item:ServiceControlItem){setEditing(item);setServiceName(item.description);setUnit(item.unit);setTotalValue(item.contractedValue);setContractedQty(item.contractedQuantity.toString().replace('.',','));setServiceNotes('');window.scrollTo({top:0,behavior:'smooth'});}
 async function saveService(){if(!scope||!control||!serviceName.trim()||numberOf(contractedQty)<=0||totalValue<=0)return;setLoading(true);setError('');try{if(editing)await updateServiceControlItem(scope,editing.id,serviceName,unit,numberOf(contractedQty),totalValue);else await addServiceControlItem(scope,control.id,serviceName,unit,numberOf(contractedQty),numberOf(totalValue));resetService();await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar serviço.');setLoading(false);}}
 async function removeService(item:ServiceControlItem){if(!scope)return;setLoading(true);try{await deleteServiceControlItem(scope,item.id);if(editing?.id===item.id)resetService();setPendingDelete(null);await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao excluir serviço.');setLoading(false);}}
 async function saveEntry(){if(!scope||!control||!entryItem||numberOf(quantity)<=0)return;setLoading(true);setError('');try{await addServiceControlEntry(scope,control.id,entryItem,date,numberOf(quantity),notes);setQuantity('');setNotes('');await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar lançamento.');setLoading(false);}}
 return <div className="service-control">
  <div className="service-control__heading"><div><h1>Controle de Serviço</h1><p>Cadastre os serviços do contrato e acompanhe a execução por metragem.</p></div><Input label="Competência" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div>
  <Card title="Contrato / Obra"><div className="service-control__contract service-control__contract--simple"><Select label="Contrato / Obra" value={selectedContractId} onChange={e=>{setSelectedContractId(e.target.value);resetService();}} options={contractOptions}/></div></Card>
  {error&&<p className="ui-error">{error}</p>}{loading&&<p className="ui-muted">Atualizando…</p>}
  {selectedContract&&control&&<><div className="service-control__dashboard"><Card title="Valor dos serviços"><strong>{currency.format(totals.contracted)}</strong></Card><Card title="Executado / Medido"><strong>{currency.format(totals.acc)}</strong><small>{totals.contracted?((totals.acc/totals.contracted)*100).toFixed(1):'0.0'}%</small></Card><Card title="Saldo dos serviços"><strong>{currency.format(totals.remaining)}</strong></Card><Card title="Serviços cadastrados"><strong>{rows.length}</strong></Card></div><Card title={editing?'Editar serviço':'Cadastrar serviço para controle'}><div className="service-control__register"><Input label="Serviço" value={serviceName} onChange={e=>setServiceName(e.target.value)} placeholder="Digite o nome do serviço…"/><Select label="Unidade" value={unit} onChange={e=>setUnit(e.target.value)} options={[{value:'m',label:'m (metro)'},{value:'m²',label:'m² (metro quadrado)'},{value:'un',label:'un (unidade)'}]}/><MoneyInput label="Valor total do serviço (R$)" value={totalValue} onValueChange={setTotalValue}/><Input label="Metragem contratada" inputMode="decimal" value={contractedQty} onChange={e=>setContractedQty(e.target.value)} placeholder="0,00"/><div className="service-control__calculated"><span>Valor por {unit==='un'?'unidade':'metro'}</span><strong>{currency.format(calculatedUnit)}</strong></div><Input label="Observação (opcional)" value={serviceNotes} onChange={e=>setServiceNotes(e.target.value)} placeholder="Observação do serviço…"/><div className="service-control__register-actions">{editing&&<Button variant="secondary" onClick={resetService}>Cancelar</Button>}<Button onClick={()=>void saveService()} disabled={loading||!serviceName.trim()||numberOf(contractedQty)<=0||totalValue<=0}>{editing?'Salvar alteração':'＋ Adicionar ao controle'}</Button></div></div></Card>
  <Card title="Serviços no controle deste contrato"><div className="service-control__table service-control__table--screen"><table><thead><tr><th>#</th><th>Serviço</th><th>Unidade</th><th>Contratado</th><th>Valor / un.</th><th>Executado</th><th>Saldo</th><th>%</th><th>Ações</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={9} className="service-control__empty">Nenhum serviço cadastrado. Adicione acima somente o que deseja controlar.</td></tr>:rows.map((r,index)=><tr key={r.id}><td>{index+1}</td><td>{r.description}</td><td>{r.unit}</td><td>{qty(r.contractedQuantity)} · {currency.format(r.contractedValue)}</td><td>{currency.format(r.unitPrice)}</td><td>{qty(r.acc)} · {currency.format(r.accValue)}</td><td>{qty(r.remaining)} · {currency.format(r.remainingValue)}</td><td>{r.percent.toFixed(1)}%</td><td><div className="service-control__actions"><Button size="sm" variant="secondary" onClick={()=>editService(r)}>✎</Button><Button size="sm" variant="secondary" onClick={()=>setPendingDelete(r)}>🗑</Button></div></td></tr>)}</tbody></table></div></Card>
  <Card title="Lançar execução"><div className="service-control__entry"><Select label="Serviço" value={entryItem} onChange={e=>setEntryItem(e.target.value)} options={itemOptions}/><Input label="Data" type="date" value={date} onChange={e=>setDate(e.target.value)}/><Input label="Metragem executada" inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="0,00"/><Input label="Observação (opcional)" value={notes} onChange={e=>setNotes(e.target.value)}/><Button onClick={()=>void saveEntry()} disabled={loading||!entryItem||numberOf(quantity)<=0}>Salvar lançamento</Button></div></Card>
  <section className="service-control__report" id="service-control-report"><div className="service-control__report-head"><div><h2>Fechamento mensal · Controle de Serviço</h2><p>{selectedContract.workName} · {selectedContract.contractNumber} · {month.split('-').reverse().join('/')}</p></div><div className="report-actions"><Button size="sm" variant="secondary" onClick={()=>window.print()}>Imprimir</Button><Button size="sm" variant="secondary" onClick={()=>{const el=document.getElementById('service-control-report');if(el)void sharePrintableElement(el,'Controle de Serviço '+selectedContract.workName+' '+month,'landscape');}}>Compartilhar PDF</Button></div></div>
   <div className="service-control__summary"><span>Contratado (serviços no controle)<strong>{currency.format(totals.contracted)}</strong></span><span>Executado no mês<strong>{currency.format(totals.monthly)}</strong><small>{totals.contracted?((totals.monthly/totals.contracted)*100).toFixed(1):'0.0'}%</small></span><span>Saldo dos serviços<strong>{currency.format(totals.remaining)}</strong><small>{totals.contracted?((totals.remaining/totals.contracted)*100).toFixed(1):'0.0'}%</small></span><span>Lançamentos no mês<strong>{control.entries.filter(e=>e.executionDate.slice(0,7)===month).length}</strong></span></div>
   <div className="service-control__table"><table><thead><tr><th>Serviço</th><th>Contratado</th><th>Unitário</th><th>Mês</th><th>Valor mês</th><th>Acumulado</th><th>%</th><th>Saldo</th><th>Saldo R$</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.description}</td><td>{qty(r.contractedQuantity)} {r.unit}</td><td>{currency.format(r.unitPrice)}</td><td>{qty(r.monthly)} {r.unit}</td><td>{currency.format(r.monthlyValue)}</td><td>{qty(r.acc)} {r.unit}</td><td>{r.percent.toFixed(1)}%</td><td>{qty(r.remaining)} {r.unit}</td><td>{currency.format(r.remainingValue)}</td></tr>)}</tbody></table></div>
  </section>{pendingDelete&&<div className="service-control__confirm" role="dialog" aria-modal="true" aria-label="Confirmar exclusão"><div className="service-control__confirm-card"><h3>Excluir serviço?</h3><p>O serviço <strong>{pendingDelete.description}</strong> será removido do Controle de Serviço.</p><div><Button variant="secondary" onClick={()=>setPendingDelete(null)}>Cancelar</Button><Button variant="danger" onClick={()=>void removeService(pendingDelete)} disabled={loading}>Excluir</Button></div></div></div>}</>}
 </div>;
}