import { useEffect, useMemo, useState } from 'react';
import { Button } from '../../../shared/ui/Button';
import { Select } from '../../../shared/ui/Select';
import { EmptyState, LoadingState } from '../../../shared/ui/Feedback';
import { loadMeasurementParity, type MeasurementParityModel } from '../infrastructure/LegacyMeasurementParityRepository';

interface Props{scope:{tenantId:string;companyId:string};contractId:string;contractNumber:string;workName:string}
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const qty=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:3});
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]??c));

export function EngineeringContractBalanceReport({scope,contractId,contractNumber,workName}:Props){
 const [model,setModel]=useState<MeasurementParityModel|null>(null);const [error,setError]=useState('');const [originId,setOriginId]=useState('all');
 useEffect(()=>{let active=true;setError('');void loadMeasurementParity({tenantId:scope.tenantId,companyId:scope.companyId},contractId).then(v=>{if(active)setModel(v)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Não foi possível carregar o saldo do contrato.')});return()=>{active=false}},[scope.tenantId,scope.companyId,contractId]);
 const origins=useMemo(()=>model?.origins.filter(o=>o.type==='tower'||o.type==='addendum')??[],[model]);
 const selected=originId==='all'?origins:origins.filter(o=>o.id===originId);
 const rows=useMemo(()=>selected.flatMap(origin=>origin.services.map(service=>{const lines=(model?.lines??[]).filter(l=>l.targetKind===service.targetKind&&l.targetId===service.targetId);const measured=lines.reduce((s,l)=>s+l.measuredQuantity,0);const measuredValue=lines.reduce((s,l)=>s+(l.exactGrossValue??l.measuredQuantity*(l.unitPriceSnapshot||service.unitPrice)),0);const remaining=Math.max(0,service.contractedQuantity-measured);const refs=[...new Set(lines.map(l=>l.reference).filter((v):v is string=>Boolean(v)))];const configured=service.scopeUnits.length?service.scopeUnits:service.scopeFloors;const pending=configured.length?configured.filter(v=>!refs.some(r=>r.toLocaleLowerCase('pt-BR').includes(v.toLocaleLowerCase('pt-BR')))):[];return {origin,service,measured,measuredValue,remaining,balance:Math.max(0,service.contractedQuantity*service.unitPrice-measuredValue),pending};})),[selected,model]);
 const totals=rows.reduce((a,r)=>({contracted:a.contracted+r.service.contractedQuantity*r.service.unitPrice,measured:a.measured+r.measuredValue,balance:a.balance+r.balance}),{contracted:0,measured:0,balance:0});
 function print(){
   const old=document.getElementById('contract-balance-print-root');old?.remove();document.getElementById('contract-balance-print-style')?.remove();
   const root=document.createElement('div');root.id='contract-balance-print-root';
   const groups=selected.map(origin=>{const rs=rows.filter(r=>r.origin.id===origin.id);const subtotal=rs.reduce((s,r)=>s+r.balance,0);return `<section class="group"><h2><span>${esc(origin.name)}</span><b>Saldo ${money.format(subtotal)}</b></h2><table><thead><tr><th>Cód.</th><th>Serviço</th><th>Un.</th><th>Qtd. contratada</th><th>Qtd. medida</th><th>Qtd. saldo</th><th>V. unit.</th><th>Saldo</th><th>Falta medir / localização</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${esc(r.service.code||'—')}</td><td><strong>${esc(r.service.description)}</strong></td><td>${esc(r.service.unit)}</td><td class="num">${qty.format(r.service.contractedQuantity)}</td><td class="num">${qty.format(r.measured)}</td><td class="num"><strong>${qty.format(r.remaining)}</strong></td><td class="num">${money.format(r.service.unitPrice)}</td><td class="num"><strong>${money.format(r.balance)}</strong></td><td>${r.pending.length?esc(r.pending.join(', ')):(r.remaining>0?'Saldo pendente sem unidade individual cadastrada':'Concluído')}</td></tr>`).join('')}</tbody></table></section>`}).join('');
   root.innerHTML=`<div class="watermark"><img src="/company-cr.svg"></div><header><img src="/company-cr.svg"><div><h1>Saldo do contrato</h1><strong>${esc(workName)}</strong><span>Contrato ${esc(contractNumber)} · ${originId==='all'?'Contrato completo':esc(selected[0]?.name??'')}</span></div></header><main><div class="totals"><div><span>Contratado</span><b>${money.format(totals.contracted)}</b></div><div><span>Medido</span><b>${money.format(totals.measured)}</b></div><div><span>Saldo atual</span><b>${money.format(totals.balance)}</b></div></div>${groups}</main>`;
   const style=document.createElement('style');style.id='contract-balance-print-style';style.textContent=`#contract-balance-print-root{position:fixed;left:-100000px;top:0;width:1100px;visibility:hidden;background:#fff;color:#111827}@media print{@page{size:A4 landscape;margin:16mm 8mm 9mm}body>*{display:none!important}#contract-balance-print-root{display:block!important;position:static!important;left:auto!important;width:auto!important;visibility:visible!important;font-family:Arial,sans-serif!important;font-size:8px!important}#contract-balance-print-root *{box-sizing:border-box!important;visibility:visible!important}#contract-balance-print-root header{display:flex!important;justify-content:space-between!important;align-items:center!important;border-bottom:2px solid #1d4ed8!important;padding-bottom:5px!important;margin-bottom:8px!important}#contract-balance-print-root header>img{width:150px!important;max-height:45px!important;object-fit:contain!important;object-position:left center!important}#contract-balance-print-root header>div{text-align:right!important}#contract-balance-print-root h1{font-size:16px!important;margin:0 0 2px!important}#contract-balance-print-root header span{display:block!important;margin-top:2px!important}.watermark{position:fixed!important;inset:0!important;display:flex!important;align-items:center!important;justify-content:center!important;opacity:.045!important;z-index:0!important}.watermark img{width:120mm!important}.totals{display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:6px!important;margin-bottom:8px!important}.totals div{border:1px solid #dbe3ef!important;border-radius:6px!important;padding:6px!important}.totals span{display:block!important;color:#64748b!important}.totals b{font-size:11px!important}.group{position:relative!important;z-index:1!important;margin-bottom:8px!important}.group h2{display:flex!important;justify-content:space-between!important;background:#eef2ff!important;border:1px solid #dbe3ef!important;padding:5px 7px!important;margin:0!important;font-size:10px!important;break-after:avoid!important}table{width:100%!important;border-collapse:collapse!important;table-layout:fixed!important}thead{display:table-header-group!important}tr{break-inside:avoid!important}th,td{border:1px solid #e5e7eb!important;padding:3px!important;vertical-align:top!important;overflow-wrap:anywhere!important}th{background:#f8fafc!important;font-size:7px!important;text-transform:uppercase!important}.num{text-align:right!important}th:nth-child(1){width:6%}th:nth-child(2){width:25%}th:nth-child(3){width:5%}th:nth-child(4),th:nth-child(5),th:nth-child(6){width:8%}th:nth-child(7),th:nth-child(8){width:9%}th:nth-child(9){width:22%}}`;document.head.appendChild(style);document.body.appendChild(root);requestAnimationFrame(()=>requestAnimationFrame(()=>window.print()));
 }
 if(error)return <EmptyState title="Saldo indisponível" message={error}/>;
 if(!model)return <LoadingState label="Carregando saldo detalhado do contrato…"/>;
 return <div className="engineering-contract-balance-report"><div className="engineering-sheet__toolbar"><Select label="Imprimir" value={originId} onChange={e=>setOriginId(e.target.value)} options={[{value:'all',label:'Contrato completo'},...origins.map(o=>({value:o.id,label:o.name}))]}/><Button onClick={print}>⎙ Imprimir saldo do contrato</Button></div><div className="engineering-sheet__stats"><div><span>Origens</span><strong>{selected.length}</strong></div><div><span>Contratado</span><strong>{money.format(totals.contracted)}</strong></div><div><span>Medido</span><strong>{money.format(totals.measured)}</strong></div><div><span>Saldo</span><strong>{money.format(totals.balance)}</strong></div></div><div className="engineering-sheet__table-wrap"><table className="engineering-sheet__table"><thead><tr><th>Origem</th><th>Código</th><th>Serviço</th><th>Qtd.</th><th>Medido</th><th>Saldo qtd.</th><th>Saldo R$</th><th>Falta medir</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.origin.id}-${r.service.targetKind}-${r.service.targetId}`}><td><strong>{r.origin.name}</strong></td><td>{r.service.code||'—'}</td><td>{r.service.description}</td><td>{qty.format(r.service.contractedQuantity)}</td><td>{qty.format(r.measured)}</td><td><strong>{qty.format(r.remaining)}</strong></td><td><strong>{money.format(r.balance)}</strong></td><td>{r.pending.length?r.pending.join(', '):(r.remaining>0?'Pendente':'Concluído')}</td></tr>)}</tbody></table>{rows.length===0&&<EmptyState title="Sem serviços" message="Não há serviços nesta origem."/ >}</div></div>;
}
