import { useCallback,useEffect,useMemo,useState } from 'react';
import type { CompanySummary } from '../../platform/domain/AccessContext';
import { Button } from '../../../shared/ui/Button';
import { deleteTravelBudget,listTravelBudgets,saveTravelBudget,type TravelBudget,type TravelBudgetDraft } from '../infrastructure/TravelBudgetRepository';

const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const today=()=>new Date().toISOString().slice(0,10);
const categories=['Combustível','Pedágios','Hospedagem','Alimentação','Deslocamentos locais','Estacionamento','Passeios','Outros'];
const blankItems=()=>categories.map((category,index)=>({category,description:category,plannedAmount:0,actualAmount:0,dueDate:null as string|null,sortOrder:index+1}));
export function TravelBudgetPage({companies,initialCompanyId}:{companies:readonly CompanySummary[];initialCompanyId?:string}){
 const [companyId,setCompanyId]=useState(initialCompanyId??companies[0]?.id??''); const company=companies.find(c=>c.id===companyId)??companies[0];
 const [rows,setRows]=useState<TravelBudget[]>([]);const [editing,setEditing]=useState<TravelBudget|null>(null);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [form,setForm]=useState(()=>({name:'Nova viagem',origin:'',destination:'',startDate:today(),endDate:today(),travelers:2,vehicleName:'',fuelType:'Etanol',fuelPrice:0,avgConsumption:10,totalDistanceKm:0,reservePercent:10,notes:'',items:blankItems()}));
 const load=useCallback(async()=>{if(!company)return;try{setRows(await listTravelBudgets(company.tenantId,company.id));setError('');}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar viagens.');}},[company]);
 useEffect(()=>{void load();},[load]);
 const fuel=Math.max(0,form.avgConsumption)>0?(Math.max(0,form.totalDistanceKm)/form.avgConsumption)*Math.max(0,form.fuelPrice):0;
 const base=useMemo(()=>fuel+form.items.reduce((s,i)=>s+(i.category==='Combustível'?0:Math.max(0,i.plannedAmount)),0),[fuel,form.items]);
 const reserve=base*Math.max(0,form.reservePercent)/100,total=base+reserve,actual=form.items.reduce((s,i)=>s+Math.max(0,i.actualAmount),0),available=total-actual;
 const startNew=()=>{setEditing(null);setForm({name:'Nova viagem',origin:'',destination:'',startDate:today(),endDate:today(),travelers:2,vehicleName:'',fuelType:'Etanol',fuelPrice:0,avgConsumption:10,totalDistanceKm:0,reservePercent:10,notes:'',items:blankItems()});setOpen(true);};
 const edit=(r:TravelBudget)=>{setEditing(r);setForm({name:r.name,origin:r.origin,destination:r.destination,startDate:r.startDate,endDate:r.endDate,travelers:r.travelers,vehicleName:r.vehicleName,fuelType:r.fuelType,fuelPrice:r.fuelPrice,avgConsumption:r.avgConsumption,totalDistanceKm:r.totalDistanceKm,reservePercent:r.reservePercent,notes:r.notes,items:r.items.map(i=>({category:i.category,description:i.description,plannedAmount:i.plannedAmount,actualAmount:i.actualAmount,dueDate:i.dueDate,sortOrder:i.sortOrder}))});setOpen(true);};
 const save=async()=>{if(!company||!form.name.trim()||form.endDate<form.startDate)return;setBusy(true);try{const items=form.items.map(i=>i.category==='Combustível'?{...i,plannedAmount:fuel}:i);const draft:TravelBudgetDraft={...(editing?{id:editing.id}:{}),tenantId:company.tenantId,companyId:company.id,...form,items};await saveTravelBudget(draft);setOpen(false);await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar viagem.');}finally{setBusy(false);}};
 return <section className="app-company-sections"><header className="app-page__section-header"><div><small>ORÇAMENTO PESSOAL</small><h1>Viagens</h1><p>Planeje a viagem sem movimentar o saldo bancário antes do gasto acontecer.</p></div><Button onClick={startNew}>Nova viagem</Button></header>
 {companies.length>1&&<label>Empresa <select value={companyId} onChange={e=>setCompanyId(e.target.value)}>{companies.map(c=><option key={c.id} value={c.id}>{c.tradeName??c.legalName}</option>)}</select></label>}
 {error&&<p role="alert">{error}</p>}
 {!open&&<div className="app-card-grid">{rows.map(r=>{const plannedFuel=r.avgConsumption>0?(r.totalDistanceKm/r.avgConsumption)*r.fuelPrice:0;const plannedBase=plannedFuel+r.items.filter(i=>i.category!=='Combustível').reduce((s,i)=>s+i.plannedAmount,0);const planned=plannedBase*(1+r.reservePercent/100);const spent=r.items.reduce((s,i)=>s+i.actualAmount,0);return <article className="app-card" key={r.id}><small>{r.startDate} → {r.endDate}</small><h2>{r.name}</h2><p>{r.origin} → {r.destination} · {r.travelers} pessoa(s)</p><p><strong>Previsto {money.format(planned)}</strong> · Realizado {money.format(spent)} · Disponível {money.format(planned-spent)}</p><Button size="sm" variant="secondary" onClick={()=>edit(r)}>Editar</Button> <Button size="sm" variant="tertiary" onClick={()=>void (async()=>{if(!company||!window.confirm('Excluir este orçamento de viagem?'))return;await deleteTravelBudget(company.tenantId,company.id,r.id);await load();})()}>Excluir</Button></article>})}{rows.length===0&&<p>Nenhuma viagem cadastrada.</p>}</div>}
 {open&&<div className="app-card"><h2>{editing?'Editar viagem':'Nova viagem'}</h2><div className="app-form-grid">
 <label>Nome<input value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></label><label>Origem<input value={form.origin} onChange={e=>setForm(f=>({...f,origin:e.target.value}))}/></label><label>Destino<input value={form.destination} onChange={e=>setForm(f=>({...f,destination:e.target.value}))}/></label>
 <label>Ida<input type="date" value={form.startDate} onChange={e=>setForm(f=>({...f,startDate:e.target.value}))}/></label><label>Volta<input type="date" value={form.endDate} onChange={e=>setForm(f=>({...f,endDate:e.target.value}))}/></label><label>Pessoas<input type="number" min="1" value={form.travelers} onChange={e=>setForm(f=>({...f,travelers:Number(e.target.value)}))}/></label>
 <label>Veículo<input value={form.vehicleName} onChange={e=>setForm(f=>({...f,vehicleName:e.target.value}))}/></label><label>Combustível<input value={form.fuelType} onChange={e=>setForm(f=>({...f,fuelType:e.target.value}))}/></label><label>Preço/L<input type="number" step=".01" value={form.fuelPrice} onChange={e=>setForm(f=>({...f,fuelPrice:Number(e.target.value)}))}/></label><label>Consumo km/L<input type="number" step=".1" value={form.avgConsumption} onChange={e=>setForm(f=>({...f,avgConsumption:Number(e.target.value)}))}/></label><label>Distância total km<input type="number" value={form.totalDistanceKm} onChange={e=>setForm(f=>({...f,totalDistanceKm:Number(e.target.value)}))}/></label><label>Margem %<input type="number" value={form.reservePercent} onChange={e=>setForm(f=>({...f,reservePercent:Number(e.target.value)}))}/></label></div>
 <h3>Custos</h3>{form.items.map((item,index)=><div className="app-form-grid" key={item.category}><strong>{item.category}</strong><label>Previsto<input type="number" step=".01" disabled={item.category==='Combustível'} value={item.category==='Combustível'?fuel:item.plannedAmount} onChange={e=>setForm(f=>({...f,items:f.items.map((x,n)=>n===index?{...x,plannedAmount:Number(e.target.value)}:x)}))}/></label><label>Realizado<input type="number" step=".01" value={item.actualAmount} onChange={e=>setForm(f=>({...f,items:f.items.map((x,n)=>n===index?{...x,actualAmount:Number(e.target.value)}:x)}))}/></label></div>)}
 <p><strong>Base {money.format(base)} · Reserva {money.format(reserve)} · Previsto {money.format(total)} · Realizado {money.format(actual)} · Disponível {money.format(available)}</strong></p><label>Observações<textarea value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></label><div><Button disabled={busy} onClick={()=>void save()}>{busy?'Salvando…':'Salvar viagem'}</Button> <Button variant="secondary" onClick={()=>setOpen(false)}>Cancelar</Button></div></div>}
 </section>;
}
