import { useEffect, useMemo, useState } from 'react';
import { getFinanceRepositories } from '../../finance/infrastructure/createFinanceRepositories';
import type { InstallmentMaintenanceScope } from '../../finance/application/FinancialEntryRepository';
import type { FinancialEntryListItem } from '../../finance/domain/entries';
import type { FinancialAccount } from '../../finance/domain/registries';
import { Button } from '../../../shared/ui/Button';
import { Card } from '../../../shared/ui/Card';
import { Dialog } from '../../../shared/ui/Dialog';
import { Feedback } from '../../../shared/ui/Feedback';
import { Input } from '../../../shared/ui/Input';
import { MoneyInput } from '../../../shared/ui/MoneyInput';
import { Select } from '../../../shared/ui/Select';
import type { HomeEntry } from './useHomeOverview';
import './planning-payments.css';

export type PlanningDirectAction={item:HomeEntry;kind:'payment'|'edit'|'delete';nonce:string};
interface PlanningPaymentsDialogProps{open:boolean;entries:readonly HomeEntry[];onClose:()=>void;onChanged:()=>void;directAction?:PlanningDirectAction|null;onDirectActionConsumed?:()=>void;}
type ActionKind='payment'|'edit'|'delete'|null; type PaymentMode='total'|'partial'; type PaymentSummary={original:number;paid:number;remaining:number};
const finance=getFinanceRepositories(); const currency=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}); const money=(value:number)=>currency.format(value); const today=()=>new Date().toISOString().slice(0,10); const dateLabel=(value:string)=>value.split('-').reverse().join('/'); const actionKey=(prefix:string)=>`${prefix}:${crypto.randomUUID()}`; const actualInstallmentId=(item:HomeEntry)=>item.sourceKind==='financial_installment'?item.installmentId.replace(/^financial:/,''):item.installmentId;
function parseCardItem(item:HomeEntry){const match=/^card:([0-9a-f-]{36}):(\d{4}-\d{2}-\d{2})$/i.exec(item.installmentId);return match?{cardId:match[1]!,statementMonth:match[2]!}:null;}

export function PlanningPaymentsDialog({open,entries,onClose,onChanged,directAction=null,onDirectActionConsumed}:PlanningPaymentsDialogProps){
 const[from,setFrom]=useState('');const[to,setTo]=useState('');const[selected,setSelected]=useState<readonly string[]>([]);const[action,setAction]=useState<ActionKind>(null);const[target,setTarget]=useState<HomeEntry|null>(null);const[accounts,setAccounts]=useState<readonly FinancialAccount[]>([]);const[loadedEntry,setLoadedEntry]=useState<FinancialEntryListItem|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[success,setSuccess]=useState<string|null>(null);const[paymentMode,setPaymentMode]=useState<PaymentMode>('total');const[paymentSummary,setPaymentSummary]=useState<PaymentSummary>({original:0,paid:0,remaining:0});const[overpayConfirm,setOverpayConfirm]=useState(false);const[paymentForm,setPaymentForm]=useState({accountId:'',settledOn:today(),amount:0,notes:''});const[editForm,setEditForm]=useState({description:'',dueDate:today(),amount:0});const[maintenanceScope,setMaintenanceScope]=useState<InstallmentMaintenanceScope>('single');
 const expenses=useMemo(()=>entries.filter(item=>item.entryType==='expense'&&(!from||item.dueDate>=from)&&(!to||item.dueDate<=to)).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.description.localeCompare(b.description)),[entries,from,to]);const keys=expenses.map(item=>`${item.companyId}|${item.installmentId}`);const selectedItems=expenses.filter(item=>selected.includes(`${item.companyId}|${item.installmentId}`));const selectedTotal=selectedItems.reduce((total,item)=>total+item.amount,0);const allSelected=expenses.length>0&&expenses.every(item=>selected.includes(`${item.companyId}|${item.installmentId}`));const paymentAmount=paymentForm.amount;const settlementDifference=paymentAmount-paymentSummary.remaining;const absoluteDifference=Math.abs(settlementDifference);const differsFromRemaining=absoluteDifference>0.005;const remainingAfter=paymentMode==='total'?0:Math.max(paymentSummary.remaining-paymentAmount,0);const receiving=target?.entryType==='income';
 function closeAction(){setAction(null);setTarget(null);setLoadedEntry(null);setError(null);setOverpayConfirm(false);setMaintenanceScope('single');}
 function toggle(item:HomeEntry){const key=`${item.companyId}|${item.installmentId}`;setSelected(current=>current.includes(key)?current.filter(value=>value!==key):[...current,key]);} function toggleAll(){setSelected(current=>allSelected?current.filter(value=>!keys.includes(value)):[...new Set([...current,...keys])]);}
 function choosePaymentMode(mode:PaymentMode){setPaymentMode(mode);setError(null);setOverpayConfirm(false);if(mode==='total')setPaymentForm(current=>({...current,amount:paymentSummary.remaining}));}
 async function openPayment(item:HomeEntry){setBusy(true);setError(null);setSuccess(null);setTarget(item);setPaymentMode('total');try{const scope={tenantId:item.tenantId,companyId:item.companyId};const accountPromise=finance.registries.listTenantAccounts(item.tenantId);let summary:PaymentSummary;let preferredAccountId='';if(item.sourceKind==='financial_installment'){const balances=await finance.settlements.listBalances(scope);const balance=balances.find(entry=>entry.installmentId===actualInstallmentId(item));summary=balance?{original:balance.installmentAmount,paid:balance.settledAmount,remaining:balance.remainingAmount}:{original:item.amount,paid:0,remaining:item.amount};}else{const card=parseCardItem(item);if(!card)throw new Error('Fatura inválida');const[statements,cards]=await Promise.all([finance.cards.listStatements(scope,card.cardId),finance.cards.listCards(scope)]);const statement=statements.find(entry=>entry.statementMonth===card.statementMonth);summary=statement?{original:statement.statementAmount,paid:statement.paidAmount,remaining:statement.remainingAmount}:{original:item.amount,paid:0,remaining:item.amount};preferredAccountId=cards.find(entry=>entry.id===card.cardId)?.defaultPaymentAccountId??'';}const accountList=(await accountPromise).filter(account=>account.status==='active');setAccounts(accountList);setPaymentSummary(summary);setPaymentForm({accountId:accountList.some(account=>account.id===preferredAccountId)?preferredAccountId:'',settledOn:today(),amount:summary.remaining,notes:''});setAction('payment');}catch{setError(item.entryType==='income'?'Não foi possível carregar os dados do recebimento.':'Não foi possível carregar os dados do pagamento.');}finally{setBusy(false);}}
 async function performPayment(){if(!target||!paymentForm.accountId||paymentAmount<=0)return;setBusy(true);setError(null);setSuccess(null);setOverpayConfirm(false);try{const scope={tenantId:target.tenantId,companyId:target.companyId};if(target.sourceKind==='financial_installment'){await finance.settlements.record({...scope,installmentId:actualInstallmentId(target),accountId:paymentForm.accountId,settledOn:paymentForm.settledOn,amount:paymentAmount,idempotencyKey:actionKey(target.entryType==='income'?'summary-receipt':'planning-payment'),notes:paymentForm.notes||null,settlesInFull:paymentMode==='total'});}else{const card=parseCardItem(target);if(!card)throw new Error('Fatura inválida');const existing=(await finance.cards.listStatements(scope,card.cardId)).find(statement=>statement.statementMonth===card.statementMonth);const statement=existing??await finance.cards.closeStatement({...scope,cardId:card.cardId,statementMonth:card.statementMonth});await finance.cards.recordStatementPayment({...scope,statementId:statement.statementId,accountId:paymentForm.accountId,paidOn:paymentForm.settledOn,amount:paymentAmount,idempotencyKey:actionKey('planning-card-payment'),notes:paymentForm.notes||null});}setSuccess(`${target.entryType==='income'?'Recebimento':'Pagamento'} de ${money(paymentAmount)} registrado com sucesso.`);setSelected(current=>current.filter(value=>value!==`${target.companyId}|${target.installmentId}`));closeAction();onChanged();}catch{setError(target.entryType==='income'?'Não foi possível registrar o recebimento. Nenhuma segunda baixa foi criada.':'Não foi possível registrar o pagamento. Nenhuma segunda baixa foi criada.');}finally{setBusy(false);}}
 function requestPayment(){if(!target||!paymentForm.accountId||paymentAmount<=0)return;setError(null);if(paymentMode==='partial'&&paymentAmount>paymentSummary.remaining+0.005){setError(`No modo parcial, o valor não pode ultrapassar o saldo restante de ${money(paymentSummary.remaining)}.`);return;}if(paymentMode==='total'&&differsFromRemaining){setOverpayConfirm(true);return;}void performPayment();}
 async function openEdit(item:HomeEntry){if(item.sourceKind!=='financial_installment')return;setBusy(true);setError(null);setSuccess(null);setTarget(item);setMaintenanceScope('single');try{const list=await finance.entries.list({tenantId:item.tenantId,companyId:item.companyId});const current=list.find(entry=>entry.installmentId===actualInstallmentId(item));if(!current)throw new Error('Lançamento não encontrado');setLoadedEntry(current);setEditForm({description:current.description,dueDate:current.dueDate,amount:current.amount});setAction('edit');}catch{setError('Não foi possível carregar o lançamento para edição.');}finally{setBusy(false);}}
 async function saveEdit(){if(!target||!loadedEntry||!editForm.description.trim()||editForm.amount<=0)return;setBusy(true);setError(null);setSuccess(null);try{await finance.entries.updateInstallmentScope({tenantId:target.tenantId,companyId:target.companyId,installmentId:loadedEntry.installmentId,scope:maintenanceScope,description:editForm.description.trim(),counterpartyName:loadedEntry.counterpartyName,categoryId:loadedEntry.categoryId,costCenterId:loadedEntry.costCenterId,dueDate:editForm.dueDate,amount:editForm.amount,notes:loadedEntry.notes});setSuccess(maintenanceScope==='following'?'Esta parcela e as seguintes foram atualizadas.':'Somente esta parcela foi atualizada.');closeAction();onChanged();}catch{setError('Não foi possível editar. Parcelas já baixadas são protegidas.');}finally{setBusy(false);}}
 async function openDelete(item:HomeEntry){if(item.sourceKind!=='financial_installment')return;setBusy(true);setError(null);setSuccess(null);setTarget(item);setMaintenanceScope('single');try{const list=await finance.entries.list({tenantId:item.tenantId,companyId:item.companyId});const current=list.find(entry=>entry.installmentId===actualInstallmentId(item));if(!current)throw new Error('Lançamento não encontrado');setLoadedEntry(current);setAction('delete');}catch{setError('Não foi possível carregar o lançamento para exclusão.');}finally{setBusy(false);}}
 async function confirmDelete(){if(!target||!loadedEntry)return;setBusy(true);setError(null);setSuccess(null);try{await finance.entries.deleteInstallmentScope({tenantId:target.tenantId,companyId:target.companyId},loadedEntry.installmentId,maintenanceScope);setSuccess(maintenanceScope==='following'?'Esta parcela e as seguintes foram excluídas.':'Somente esta parcela foi excluída.');setSelected(current=>current.filter(value=>value!==`${target.companyId}|${target.installmentId}`));closeAction();onChanged();}catch{setError('Não foi possível excluir. Parcelas já baixadas são protegidas.');}finally{setBusy(false);}}
 useEffect(()=>{if(!directAction)return;onDirectActionConsumed?.();if(directAction.kind==='payment')void openPayment(directAction.item);else if(directAction.kind==='edit')void openEdit(directAction.item);else void openDelete(directAction.item);// eslint-disable-next-line react-hooks/exhaustive-deps
 },[directAction?.nonce]);
 const accountOptions=[{value:'',label:'Selecione…'},...accounts.map(account=>({value:account.id,label:account.name}))];
 const scopeChoices=loadedEntry&&loadedEntry.installmentCount>1?<div className="payment-app__modes"><Button variant={maintenanceScope==='single'?'primary':'secondary'} onClick={()=>setMaintenanceScope('single')}>Somente esta</Button><Button variant={maintenanceScope==='following'?'primary':'secondary'} onClick={()=>setMaintenanceScope('following')}>Esta e as seguintes</Button></div>:null;
 return <>
  <Dialog open={open} title="Planejar pagamentos" description="Selecione contas para somar ou opere cada despesa aqui mesmo: editar, excluir ou pagar." onClose={onClose} onBack={onClose}><div className="planning-payments">{error&&action===null&&<Feedback tone="danger" title="Operação não concluída" message={error}/>} {success&&<Feedback tone="success" title="Concluído" message={success}/>}<div className="planning-payments__filters"><Input label="De" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><Input label="Até" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><div className="planning-payments__summary"><span>{selectedItems.length} de {expenses.length} selecionada(s)</span><strong>{money(selectedTotal)}</strong></div>{expenses.length>0&&<Button onClick={toggleAll}>{allSelected?'Limpar seleção':'Selecionar todas'}</Button>}<div className="planning-payments__list">{expenses.length===0?<p className="ui-muted">Nenhuma despesa pendente neste período.</p>:expenses.map(item=>{const key=`${item.companyId}|${item.installmentId}`;const isSelected=selected.includes(key);const installment=item.sourceKind==='financial_installment'&&item.installmentCount>1?` · Parcela ${item.installmentNumber}/${item.installmentCount}`:'';const canMaintain=item.sourceKind==='financial_installment';return <Card key={key} className={`${item.dueDate<today()?'is-danger ':''}${isSelected?'planning-item--selected':''}`.trim()}><div className="planning-payments__details"><div><span>{item.description}{installment}</span><strong>{money(item.amount)}</strong></div><div><span>{dateLabel(item.dueDate)}</span><strong>{item.companyName}{item.sourceKind==='card_statement'?' · Cartão':''}</strong></div></div><div className="planning-payments__actions"><Button size="sm" variant="primary" onClick={()=>toggle(item)}>{isSelected?'✓ Selecionado':'Selecionar'}</Button>{canMaintain&&<Button size="sm" variant="primary" onClick={()=>void openEdit(item)}>Editar</Button>}{canMaintain&&<Button size="sm" variant="danger" onClick={()=>void openDelete(item)}>Excluir</Button>}<Button size="sm" variant="success" onClick={()=>void openPayment(item)}>Pagar</Button></div></Card>;})}</div></div></Dialog>
  <Dialog open={action==='payment'} title={receiving?'Registrar recebimento':'Registrar pagamento'} description={target?.description} loading={busy} confirmLabel={receiving?'Confirmar recebimento':'Confirmar pagamento'} onClose={closeAction} onBack={closeAction} onConfirm={requestPayment}><div className="payment-app">{error&&<Feedback tone="danger" title="Operação não concluída" message={error}/>}<div className="payment-app__hero"><div><strong>{target?.description}</strong><span>{target?.installmentCount&&target.installmentCount>1?`PARCELA ${target.installmentNumber}/${target.installmentCount}`:target?.sourceKind==='card_statement'?'FATURA DE CARTÃO':'DESPESA'}</span></div></div><div className="payment-app__totals"><div><span>Total original</span><strong>{money(paymentSummary.original)}</strong></div><div><span>Já pago</span><strong>{money(paymentSummary.paid)}</strong></div><div><span>Restante</span><strong>{money(paymentSummary.remaining)}</strong></div></div><div className="payment-app__modes"><Button variant={paymentMode==='total'?'primary':'secondary'} onClick={()=>choosePaymentMode('total')}>Pagamento total</Button><Button variant={paymentMode==='partial'?'primary':'secondary'} onClick={()=>choosePaymentMode('partial')}>Pagamento parcial</Button></div><Select label="Banco" value={paymentForm.accountId} onChange={e=>setPaymentForm(c=>({...c,accountId:e.target.value}))} options={accountOptions} required/><Input label="Data efetiva" type="date" value={paymentForm.settledOn} onChange={e=>setPaymentForm(c=>({...c,settledOn:e.target.value}))}/><MoneyInput label="Valor efetivamente pago" value={paymentForm.amount} onValueChange={amount=>setPaymentForm(c=>({...c,amount}))}/><Input label="Observação" value={paymentForm.notes} onChange={e=>setPaymentForm(c=>({...c,notes:e.target.value}))}/><div className="payment-app__result"><span>Saldo restante após confirmar</span><strong>{money(remainingAfter)}</strong></div></div></Dialog>
  <Dialog open={overpayConfirm} title="Confirmar valor diferente" description={target?`Você informou ${money(paymentAmount)}, mas o saldo restante é ${money(paymentSummary.remaining)}.`:undefined} loading={busy} confirmLabel="Confirmar pagamento total" onClose={()=>setOverpayConfirm(false)} onBack={()=>setOverpayConfirm(false)} onConfirm={()=>void performPayment()}><div className="payment-app__warning"><strong>Diferença de {settlementDifference>0?'+':'-'} {money(absoluteDifference)}</strong><span>O valor efetivamente pago será registrado e a despesa considerada liquidada.</span></div></Dialog>
  <Dialog open={action==='edit'} title="Editar despesa" description={loadedEntry&&loadedEntry.installmentCount>1?`Parcela ${loadedEntry.installmentNumber}/${loadedEntry.installmentCount}. Escolha o alcance da alteração.`:'Edite esta despesa.'} loading={busy} confirmLabel="Salvar" onClose={closeAction} onBack={closeAction} onConfirm={()=>void saveEdit()}>{error&&<Feedback tone="danger" title="Não foi possível editar" message={error}/>} {scopeChoices}<div className="planning-payments__filters"><Input label="Descrição" value={editForm.description} onChange={e=>setEditForm(c=>({...c,description:e.target.value}))}/><Input label="Vencimento" type="date" value={editForm.dueDate} onChange={e=>setEditForm(c=>({...c,dueDate:e.target.value}))}/><MoneyInput label="Valor da parcela" value={editForm.amount} onValueChange={amount=>setEditForm(c=>({...c,amount}))}/></div></Dialog>
  <Dialog open={action==='delete'} title="Excluir despesa" description={loadedEntry&&loadedEntry.installmentCount>1?`Parcela ${loadedEntry.installmentNumber}/${loadedEntry.installmentCount}. Escolha o alcance da exclusão.`:target?`Excluir ${target.description}?`:undefined} loading={busy} confirmLabel="Excluir" onClose={closeAction} onBack={closeAction} onConfirm={()=>void confirmDelete()}>{error&&<Feedback tone="danger" title="Não foi possível excluir" message={error}/>} {scopeChoices}</Dialog>
 </>;
}
