import { getSupabaseClient } from '../../../shared/infrastructure/supabase/client';

export type EngineeringCommercialBudgetStatus='Em andamento'|'Aprovado'|'Recusado'|'Cancelado'|'Contrato';
export interface EngineeringCommercialBudgetItem{ id:string;category:string;subcategory:string;description:string;quantity:number;unit:string;unitPrice:number; }
export interface EngineeringCommercialBudget{ id:string;tenantId:string;companyId:string;title:string;issuer:string;customer:string;project:string;issueDate:string;validityDays:number;paymentTerms:string;notes:string;total:number;targetMarginPercent:number;status:EngineeringCommercialBudgetStatus;items:EngineeringCommercialBudgetItem[];contractId:string|null;convertedAt:string|null;updatedAt:string; }
export interface EngineeringCommercialBudgetDraft{ id?:string;tenantId:string;companyId:string;title:string;issuer:string;customer:string;project:string;issueDate:string;validityDays:number;paymentTerms:string;notes:string;targetMarginPercent:number;status:EngineeringCommercialBudgetStatus;items:EngineeringCommercialBudgetItem[]; }
type Row={id:string;tenant_id:string;company_id:string;title:string;issuer:string;customer:string;project:string;issue_date:string;validity_days:number;payment_terms:string;notes:string;total:number|string;target_margin_percent:number|string;status:EngineeringCommercialBudgetStatus;items:unknown;contract_id:string|null;converted_at:string|null;updated_at:string};
const toBudget=(row:Row):EngineeringCommercialBudget=>({id:row.id,tenantId:row.tenant_id,companyId:row.company_id,title:row.title,issuer:row.issuer,customer:row.customer,project:row.project,issueDate:row.issue_date,validityDays:Number(row.validity_days),paymentTerms:row.payment_terms,notes:row.notes,total:Number(row.total),targetMarginPercent:Number(row.target_margin_percent??20),status:row.status,items:Array.isArray(row.items)?row.items as EngineeringCommercialBudgetItem[]:[],contractId:row.contract_id,convertedAt:row.converted_at,updatedAt:row.updated_at});
export async function listEngineeringCommercialBudgets(scopes:readonly {tenantId:string;companyId:string}[]){const client=getSupabaseClient();const all:EngineeringCommercialBudget[]=[];for(const scope of scopes){const result=await client.from('engineering_budgets').select('id,tenant_id,company_id,title,issuer,customer,project,issue_date,validity_days,payment_terms,notes,total,target_margin_percent,status,items,contract_id,converted_at,updated_at').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).order('updated_at',{ascending:false}).returns<Row[]>();if(result.error)throw result.error;all.push(...(result.data??[]).map(toBudget));}return all.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));}
export async function saveEngineeringCommercialBudget(draft:EngineeringCommercialBudgetDraft){const client=getSupabaseClient();const total=draft.items.reduce((sum,item)=>sum+Math.max(0,item.quantity)*Math.max(0,item.unitPrice),0);const payload={tenant_id:draft.tenantId,company_id:draft.companyId,title:draft.title.trim(),issuer:draft.issuer.trim(),customer:draft.customer.trim(),project:draft.project.trim(),issue_date:draft.issueDate,validity_days:draft.validityDays,payment_terms:draft.paymentTerms.trim(),notes:draft.notes.trim(),target_margin_percent:Math.max(0,Math.min(99.99,draft.targetMarginPercent)),status:draft.status,total,items:draft.items,updated_at:new Date().toISOString()};if(draft.id){const result=await client.from('engineering_budgets').update(payload).eq('id',draft.id).eq('tenant_id',draft.tenantId).eq('company_id',draft.companyId).select('id').single();if(result.error)throw result.error;return String(result.data.id);}const result=await client.from('engineering_budgets').insert(payload).select('id').single();if(result.error)throw result.error;return String(result.data.id);}
export async function setEngineeringCommercialBudgetStatus(id:string,status:EngineeringCommercialBudgetStatus){const client=getSupabaseClient();const result=await client.from('engineering_budgets').update({status,updated_at:new Date().toISOString()}).eq('id',id).select('id').single();if(result.error)throw result.error;}
export async function deleteEngineeringCommercialBudget(id:string){const client=getSupabaseClient();const result=await client.from('engineering_budgets').delete().eq('id',id);if(result.error)throw result.error;}
export async function convertEngineeringCommercialBudgetToContract(id:string){const client=getSupabaseClient();const result=await client.rpc('convert_engineering_budget_to_contract',{p_budget_id:id});if(result.error)throw result.error;return String(result.data);}
