import type { SupabaseClient } from '@supabase/supabase-js';
import type { EngineeringOperationalSnapshot, EngineeringOperationsRepository, EngineeringScope } from '../application/EngineeringOperationsRepository';

type WorkRow={id:string;name:string};
type StructureRow={id:string;name:string;work_id:string;parent_id:string|null;structure_type:string;code:string|null;metadata:Record<string,unknown>|null};
type ServiceRow={id:string;name:string;default_unit:string};
type ContractRow={id:string;contract_number:string;work_id:string;status:string};
type ContractServiceRow={id:string;contract_id:string;description:string;unit:string;contracted_quantity:number|string;unit_price:number|string};
type MeasurementRow={id:string;contract_id:string;competence:string;status:string;measurement_number:string|null;due_date:string|null;expected_payment_date:string|null;payment_method:string|null;origin_label:string|null;notes:string|null};
type PeriodRow={id:string;work_id:string;competence:string;status:string};
type EmployeeRow={id:string;employees:{full_name:string}[]};
type ProvisionalRow={id:string;provisional_number:string;status:string;work_id:string;title:string|null;client_name:string|null};
type ProvisionalLineRow={id:string;provisional_id:string;service_id:string|null;description:string;unit:string;quantity:number|string;unit_price:number|string};
type AddendumRow={id:string;contract_id:string;addendum_number:string;status:string};
type AllocationRow={id:string;contract_service_id:string;structure_id:string;allocated_quantity:number|string;status:string;notes:string|null;scope_config:Record<string,unknown>|null};
type MeasurementLineRow={id:string;measurement_id:string;contract_service_id:string;structure_id:string|null;measured_quantity:number|string;gross_value:number|string};
type AccountRow={account_id:string;name:string;status:string};
type ContractRetentionRulePayload={tenant_id:string;company_id:string;contract_id:string;retention_type:'inss'|'iss'|'rt';calculation_type:'percentage';rate:number;fixed_amount:null;active:boolean};

function required(value:string,field:string){const normalized=value.trim();if(!normalized)throw new Error(`${field} é obrigatório`);return normalized;}
function nonNegative(value:number,field:string){if(!Number.isFinite(value)||value<0||Math.round(value*100)!==value*100)throw new Error(`${field} inválido`);return value;}
function positive(value:number,field:string){if(!Number.isFinite(value)||value<=0)throw new Error(`${field} inválido`);return value;}
function percentage(value:number|undefined|null,field:string){const normalized=value??0;if(!Number.isFinite(normalized)||normalized<0||normalized>=100)throw new Error(`${field} inválido`);return normalized;}
function month(value:string){const normalized=required(value,'Competência');return /^\d{4}-\d{2}-01$/.test(normalized)?normalized:`${normalized.slice(0,7)}-01`;}

export class SupabaseEngineeringOperationsRepository implements EngineeringOperationsRepository {
  constructor(private readonly client:SupabaseClient){}

  async getSnapshot(scope:EngineeringScope):Promise<EngineeringOperationalSnapshot>{
    const [works,structures,services,contracts,contractServices,measurements,periods,employees,provisionals,provisionalLines,addenda,accounts,allocations,measurementLines]=await Promise.all([
      this.client.from('works').select('id,name').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).neq('status','archived').order('name').returns<WorkRow[]>(),
      this.client.from('work_structures').select('id,name,work_id,parent_id,structure_type,code,metadata').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('status','active').order('sort_order').returns<StructureRow[]>(),
      this.client.from('engineering_services').select('id,name,default_unit').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('status','active').order('name').returns<ServiceRow[]>(),
      this.client.from('engineering_contracts').select('id,contract_number,work_id,status').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).order('created_at',{ascending:false}).returns<ContractRow[]>(),
      this.client.from('contract_services').select('id,contract_id,description,unit,contracted_quantity,unit_price').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('status','active').order('created_at').returns<ContractServiceRow[]>(),
      this.client.from('measurements').select('id,contract_id,competence,status,measurement_number,due_date,expected_payment_date,payment_method,origin_label,notes').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).order('competence',{ascending:false}).returns<MeasurementRow[]>(),
      this.client.from('engineering_production_periods').select('id,work_id,competence,status').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).order('competence',{ascending:false}).returns<PeriodRow[]>(),
      this.client.from('employment_contracts').select('id,employees!inner(full_name)').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('status','active').order('hired_on').returns<EmployeeRow[]>(),
      this.client.from('provisional_contracts').select('id,provisional_number,status,work_id,title,client_name').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).order('created_at',{ascending:false}).returns<ProvisionalRow[]>(),
      this.client.from('provisional_contract_lines').select('id,provisional_id,service_id,description,unit,quantity,unit_price').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).order('created_at').returns<ProvisionalLineRow[]>(),
      this.client.from('contract_addenda').select('id,contract_id,addendum_number,status').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).order('created_at',{ascending:false}).returns<AddendumRow[]>(),
      this.client.from('financial_account_balances').select('account_id,name,status').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('status','active').order('name').returns<AccountRow[]>(),
      this.client.from('contract_service_allocations').select('id,contract_service_id,structure_id,allocated_quantity,status,notes,scope_config').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('status','active').returns<AllocationRow[]>(),
      this.client.from('measurement_lines').select('id,measurement_id,contract_service_id,structure_id,measured_quantity,gross_value').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).returns<MeasurementLineRow[]>(),
    ]);
    const error=[works.error,structures.error,services.error,contracts.error,contractServices.error,measurements.error,periods.error,employees.error,provisionals.error,provisionalLines.error,addenda.error,accounts.error,allocations.error,measurementLines.error].find(Boolean);if(error)throw error;
    return {
      works:(works.data??[]).map(row=>({id:row.id,name:row.name})),
      structures:(structures.data??[]).map(row=>({id:row.id,name:row.name,workId:row.work_id,parentId:row.parent_id,type:row.structure_type,code:row.code,metadata:row.metadata})),
      allocations:(allocations.data??[]).map(row=>({id:row.id,contractServiceId:row.contract_service_id,structureId:row.structure_id,allocatedQuantity:Number(row.allocated_quantity),status:row.status,notes:row.notes,scopeConfig:row.scope_config as EngineeringOperationalSnapshot['allocations'][number]['scopeConfig']})),
      measurementLines:(measurementLines.data??[]).map(row=>({id:row.id,measurementId:row.measurement_id,contractServiceId:row.contract_service_id,structureId:row.structure_id,measuredQuantity:Number(row.measured_quantity),grossValue:Number(row.gross_value)})),
      services:(services.data??[]).map(row=>({id:row.id,name:row.name,unit:row.default_unit})),
      contracts:(contracts.data??[]).map(row=>({id:row.id,contractNumber:row.contract_number,workId:row.work_id,status:row.status})),
      contractServices:(contractServices.data??[]).map(row=>({id:row.id,contractId:row.contract_id,description:row.description,unit:row.unit,quantity:Number(row.contracted_quantity),unitPrice:Number(row.unit_price)})),
      measurements:(measurements.data??[]).map(row=>({id:row.id,contractId:row.contract_id,competence:row.competence,status:row.status,measurementNumber:row.measurement_number??'',dueDate:row.due_date,expectedPaymentDate:row.expected_payment_date,paymentMethod:row.payment_method,originLabel:row.origin_label,notes:row.notes})),
      productionPeriods:(periods.data??[]).map(row=>({id:row.id,workId:row.work_id,competence:row.competence,status:row.status})),
      employees:(employees.data??[]).map(row=>({id:row.id,name:row.employees[0]?.full_name??''})),
      provisionals:(provisionals.data??[]).map(row=>({id:row.id,number:row.provisional_number,status:row.status,workId:row.work_id,title:row.title,clientName:row.client_name})),
      provisionalLines:(provisionalLines.data??[]).map(row=>({id:row.id,provisionalId:row.provisional_id,serviceId:row.service_id,description:row.description,unit:row.unit,quantity:Number(row.quantity),unitPrice:Number(row.unit_price)})),
      addenda:(addenda.data??[]).map(row=>({id:row.id,contractId:row.contract_id,number:row.addendum_number,status:row.status})),
      accounts:(accounts.data??[]).map(row=>({id:row.account_id,name:row.name})),
    };
  }

  async createWork(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['createWork']>[1]){const r=await this.client.from('works').insert({tenant_id:scope.tenantId,company_id:scope.companyId,name:required(input.name,'Obra'),code:input.code||null,client_name:input.clientName||null,city:input.city||null,state:input.state||null,notes:input.notes||null});if(r.error)throw r.error;}
  async createStructure(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['createStructure']>[1]){const r=await this.client.from('work_structures').insert({tenant_id:scope.tenantId,company_id:scope.companyId,work_id:required(input.workId,'Obra'),parent_id:input.parentId||null,structure_type:input.type,code:input.code||null,name:required(input.name,'Estrutura')});if(r.error)throw r.error;}
  async updateStructure(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['updateStructure']>[1]){const r=await this.client.from('work_structures').update({code:input.code||null,name:required(input.name,'Estrutura'),metadata:input.metadata??null,updated_at:new Date().toISOString()}).eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('id',required(input.structureId,'Estrutura'));if(r.error)throw r.error;}
  async createContract(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['createContract']>[1]){const contract=await this.client.from('engineering_contracts').insert({tenant_id:scope.tenantId,company_id:scope.companyId,work_id:required(input.workId,'Obra'),contract_number:required(input.contractNumber,'Número'),client_name:input.clientName||null,signed_at:input.signedAt||null,start_date:input.startDate||null,end_date:input.endDate||null,notes:input.notes||null}).select('id').single();if(contract.error)throw contract.error;const contractId:string=contract.data.id as string;const rules:ContractRetentionRulePayload[]=[{type:'inss' as const,rate:percentage(input.inssRate,'INSS')},{type:'iss' as const,rate:percentage(input.issRate,'ISS')},{type:'rt' as const,rate:percentage(input.retentionRate,'Retenção')}].filter(item=>item.rate>0).map(item=>({tenant_id:scope.tenantId,company_id:scope.companyId,contract_id:contractId,retention_type:item.type,calculation_type:'percentage',rate:item.rate,fixed_amount:null,active:true}));if(rules.length){const retention=await this.client.from('engineering_contract_retention_rules').insert(rules);if(retention.error)throw retention.error;}}
  async updateContractStatus(scope:EngineeringScope,contractId:string,status:Parameters<EngineeringOperationsRepository['updateContractStatus']>[2]){const r=await this.client.from('engineering_contracts').update({status,updated_at:new Date().toISOString()}).eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('id',required(contractId,'Contrato'));if(r.error)throw r.error;}
  async createService(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['createService']>[1]){const r=await this.client.from('engineering_services').insert({tenant_id:scope.tenantId,company_id:scope.companyId,name:required(input.name,'Serviço'),default_unit:required(input.unit,'Unidade'),code:input.code||null,category:input.category||null,notes:input.notes||null});if(r.error)throw r.error;}
  async addContractService(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['addContractService']>[1]){const r=await this.client.from('contract_services').insert({tenant_id:scope.tenantId,company_id:scope.companyId,contract_id:required(input.contractId,'Contrato'),service_id:input.serviceId||null,description:required(input.description,'Descrição'),unit:required(input.unit,'Unidade'),contracted_quantity:nonNegative(input.quantity,'Quantidade'),unit_price:nonNegative(input.unitPrice,'Valor unitário'),notes:input.notes||null});if(r.error)throw r.error;}
  async allocateContractService(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['allocateContractService']>[1]){const contractServiceId=required(input.contractServiceId,'Serviço do contrato');const structureId=required(input.structureId,'Estrutura');const nextQuantity=positive(input.quantity,'Quantidade');const payload={allocated_quantity:nextQuantity,notes:input.notes||null,scope_config:input.scopeConfig??{},status:'active',updated_at:new Date().toISOString()};const existing=await this.client.from('contract_service_allocations').select('id').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('contract_service_id',contractServiceId).eq('structure_id',structureId).maybeSingle();if(existing.error)throw existing.error;if(existing.data?.id){const r=await this.client.from('contract_service_allocations').update(payload).eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('id',existing.data.id);if(r.error)throw r.error;return;}const r=await this.client.from('contract_service_allocations').insert({tenant_id:scope.tenantId,company_id:scope.companyId,work_id:required(input.workId,'Obra'),contract_service_id:contractServiceId,structure_id:structureId,...payload});if(r.error)throw r.error;}
  async createProvisional(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['createProvisional']>[1]){const r=await this.client.from('provisional_contracts').insert({tenant_id:scope.tenantId,company_id:scope.companyId,work_id:required(input.workId,'Obra'),provisional_number:required(input.number,'Número'),title:input.title||null,client_name:input.clientName||null,notes:input.notes||null});if(r.error)throw r.error;}
  async updateProvisional(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['updateProvisional']>[1]){const r=await this.client.from('provisional_contracts').update({title:input.title||null,client_name:input.clientName||null,status:input.status,notes:input.notes||null,updated_at:new Date().toISOString()}).eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('id',required(input.provisionalId,'Provisório')).neq('status','converted');if(r.error)throw r.error;}
  async addProvisionalLine(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['addProvisionalLine']>[1]){const r=await this.client.from('provisional_contract_lines').insert({tenant_id:scope.tenantId,company_id:scope.companyId,provisional_id:required(input.provisionalId,'Provisório'),service_id:input.serviceId||null,description:required(input.description,'Descrição'),unit:required(input.unit,'Unidade'),quantity:nonNegative(input.quantity,'Quantidade'),unit_price:nonNegative(input.unitPrice,'Valor unitário'),notes:input.notes||null});if(r.error)throw r.error;}
  async updateProvisionalLine(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['updateProvisionalLine']>[1]){const provisional=await this.client.from('provisional_contracts').select('id,status').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('id',required(input.provisionalId,'Provisório')).single();if(provisional.error)throw provisional.error;if(provisional.data.status==='converted')throw new Error('Provisório convertido não pode ser alterado');const r=await this.client.from('provisional_contract_lines').update({service_id:input.serviceId||null,description:required(input.description,'Descrição'),unit:required(input.unit,'Unidade'),quantity:nonNegative(input.quantity,'Quantidade'),unit_price:nonNegative(input.unitPrice,'Valor unitário'),notes:input.notes||null,updated_at:new Date().toISOString()}).eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('provisional_id',input.provisionalId).eq('id',required(input.lineId,'Item'));if(r.error)throw r.error;}
  async convertProvisional(input:Parameters<EngineeringOperationsRepository['convertProvisional']>[0]){const r=await this.client.rpc('convert_provisional_contract',{p_provisional_id:required(input.provisionalId,'Provisório'),p_destination:input.destination,p_number:required(input.number,'Número'),p_contract_id:input.contractId||null,p_addendum_type:input.addendumType||null});if(r.error)throw r.error;}
  async createAddendum(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['createAddendum']>[1]){const r=await this.client.from('contract_addenda').insert({tenant_id:scope.tenantId,company_id:scope.companyId,contract_id:required(input.contractId,'Contrato'),addendum_number:required(input.number,'Número'),addendum_type:input.type,effective_date:input.effectiveDate||null,stated_value:input.statedValue==null?null:nonNegative(input.statedValue,'Valor'),notes:input.notes||null});if(r.error)throw r.error;}
  async addAddendumLine(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['addAddendumLine']>[1]){if(!Number.isFinite(input.quantityDelta)||input.quantityDelta===0)throw new Error('Variação de quantidade inválida');const r=await this.client.from('contract_addendum_lines').insert({tenant_id:scope.tenantId,company_id:scope.companyId,addendum_id:required(input.addendumId,'Aditivo'),contract_service_id:input.contractServiceId||null,service_id:input.serviceId||null,description:required(input.description,'Descrição'),unit:required(input.unit,'Unidade'),quantity_delta:input.quantityDelta,unit_price:nonNegative(input.unitPrice,'Valor unitário'),notes:input.notes||null});if(r.error)throw r.error;}
  async createMeasurement(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['createMeasurement']>[1]){const measurementNumber=required(input.measurementNumber,'Número da medição');const duplicate=await this.client.from('measurements').select('id').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('contract_id',required(input.contractId,'Contrato')).eq('measurement_number',measurementNumber).maybeSingle();if(duplicate.error)throw duplicate.error;if(duplicate.data)throw new Error('Já existe uma medição com este número neste contrato.');const r=await this.client.from('measurements').insert({tenant_id:scope.tenantId,company_id:scope.companyId,contract_id:input.contractId,competence:month(input.competence),measurement_number:measurementNumber,due_date:input.dueDate||null,expected_payment_date:input.expectedPaymentDate||null,payment_method:input.paymentMethod||null,origin_label:input.originLabel||null,notes:input.notes||null});if(r.error)throw r.error;}
  async updateMeasurement(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['updateMeasurement']>[1]){const id=required(input.measurementId,'Medição');const measurementNumber=required(input.measurementNumber,'Número da medição');const current=await this.client.from('measurements').select('id,status,contract_id').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('id',id).single();if(current.error)throw current.error;if(current.data.status!=='draft')throw new Error('Somente medições em rascunho podem ser editadas.');const duplicate=await this.client.from('measurements').select('id').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('contract_id',current.data.contract_id).eq('measurement_number',measurementNumber).neq('id',id).maybeSingle();if(duplicate.error)throw duplicate.error;if(duplicate.data)throw new Error('Já existe outra medição com este número neste contrato.');const r=await this.client.from('measurements').update({competence:month(input.competence),measurement_number:measurementNumber,due_date:input.dueDate||null,expected_payment_date:input.expectedPaymentDate||null,payment_method:input.paymentMethod||null,notes:input.notes||null,updated_at:new Date().toISOString()}).eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('id',id).eq('status','draft');if(r.error)throw r.error;}
  async deleteMeasurement(scope:EngineeringScope,measurementId:string){
    const id=required(measurementId,'Medição');
    const current=await this.client.from('measurements').select('status').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('id',id).single();
    if(current.error)throw current.error;
    if(current.data.status!=='draft')throw new Error('Somente medições em rascunho podem ser excluídas. Reabra a medição antes de excluir.');
    const retentions=await this.client.from('measurement_retentions').delete().eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('measurement_id',id);if(retentions.error)throw retentions.error;
    const lines=await this.client.from('measurement_lines').delete().eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('measurement_id',id);if(lines.error)throw lines.error;
    const measurement=await this.client.from('measurements').delete().eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('id',id).eq('status','draft');if(measurement.error)throw measurement.error;
  }
  async addMeasurementLine(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['addMeasurementLine']>[1]){const r=await this.client.from('measurement_lines').insert({tenant_id:scope.tenantId,company_id:scope.companyId,measurement_id:required(input.measurementId,'Medição'),contract_service_id:required(input.contractServiceId,'Serviço do contrato'),structure_id:input.structureId||null,measured_quantity:positive(input.measuredQuantity,'Quantidade'),unit_price_snapshot:nonNegative(input.unitPrice,'Valor unitário'),notes:input.notes||null});if(r.error)throw r.error;}
  async addRetention(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['addRetention']>[1]){const r=await this.client.from('measurement_retentions').insert({tenant_id:scope.tenantId,company_id:scope.companyId,measurement_id:required(input.measurementId,'Medição'),retention_type:input.retentionType,calculation_type:input.calculationType,rate:input.calculationType==='percentage'?nonNegative(input.rate??0,'Percentual'):null,fixed_amount:input.calculationType==='fixed'?nonNegative(input.fixedAmount??0,'Valor'):null,description:input.description||null,notes:input.notes||null});if(r.error)throw r.error;}
  async setMeasurementStatus(measurementId:string,action:Parameters<EngineeringOperationsRepository['setMeasurementStatus']>[1],reason?:string|null){const r=await this.client.rpc('set_measurement_status',{p_measurement_id:required(measurementId,'Medição'),p_action:action,p_reason:reason||null});if(r.error)throw r.error;}
  async generateMeasurementReceivable(measurementId:string,dueDate:string){const r=await this.client.rpc('generate_measurement_receivable',{p_measurement_id:required(measurementId,'Medição'),p_due_date:required(dueDate,'Vencimento')});if(r.error)throw r.error;}
  async receiveMeasurement(measurementId:string,accountId:string,receivedOn:string,amount:number){const r=await this.client.rpc('receive_measurement',{p_measurement_id:required(measurementId,'Medição'),p_account_id:required(accountId,'Conta'),p_received_on:required(receivedOn,'Recebimento'),p_amount:positive(amount,'Valor')});if(r.error)throw r.error;}
  async createProductionPeriod(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['createProductionPeriod']>[1]){const r=await this.client.from('engineering_production_periods').insert({tenant_id:scope.tenantId,company_id:scope.companyId,work_id:required(input.workId,'Obra'),competence:month(input.competence)});if(r.error)throw r.error;}
  async addProductionEntry(scope:EngineeringScope,input:Parameters<EngineeringOperationsRepository['addProductionEntry']>[1]){const r=await this.client.from('engineering_production_entries').insert({tenant_id:scope.tenantId,company_id:scope.companyId,production_period_id:required(input.periodId,'Período'),employment_contract_id:required(input.employmentContractId,'Colaborador'),structure_id:required(input.structureId,'Estrutura'),service_id:required(input.serviceId,'Serviço'),production_date:required(input.productionDate,'Data'),executed_quantity:positive(input.executedQuantity,'Quantidade'),unit_value:input.unitValue==null?null:nonNegative(input.unitValue,'Valor unitário'),notes:input.notes||null});if(r.error)throw r.error;}
  async setProductionPeriodStatus(periodId:string,action:Parameters<EngineeringOperationsRepository['setProductionPeriodStatus']>[1],reason?:string|null){const r=await this.client.rpc('set_engineering_production_period_status',{p_period_id:required(periodId,'Período'),p_action:action,p_reason:reason||null});if(r.error)throw r.error;}
}
