import type { SupabaseClient } from '@supabase/supabase-js';
import type { CardRepository } from '../application/CardRepository';
import { normalizeCardPurchase } from '../application/cardValidation';
import type { CardInstallment, CardPurchaseDetails, CardStatementActivity, CardStatementBalance, CardStatementItem, CloseCardStatement, ClosedCardStatement, CreateCardPurchase, CreateCreditCard, CreatedCardPurchase, CreditCard, CreditCardLimit, RecordCardStatementPayment, RecordedCardStatementPayment, UpdateCardPurchase, UpdateCreditCard } from '../domain/cards';
import type { CompanyScope, FinancialBankInstitution } from '../domain/registries';

type CardRow = { id:string; tenant_id:string; company_id:string; name:string; bank_institution:FinancialBankInstitution|null; last_four:string|null; credit_limit:number|string; closing_day:number; due_day:number; default_payment_account_id:string|null; status:CreditCard['status']; sort_order:number };
type LimitRow = { card_id:string; tenant_id:string; company_id:string; name:string; credit_limit:number|string; committed_amount:number|string; available_limit:number|string; sort_order:number };
type InstallmentRow = { id:string; tenant_id:string; company_id:string; card_id:string; transaction_id:string; installment_number:number; installment_count:number; statement_month:string; amount:number|string };
type StatementItemRow = { tenant_id:string; company_id:string; card_id:string; transaction_id:string; purchase_date:string; description:string; counterparty_name:string|null; installment_number:number; installment_count:number; installment_label:string; statement_month:string; amount:number|string; statement_id:string|null; due_date:string|null; statement_status:CardStatementItem['statementStatus'] };
type ActivityRow = { tenant_id:string; company_id:string; card_id:string; statement_month:string; activity_key:string; activity_type:CardStatementActivity['activityType']; source_id:string; activity_date:string; description:string; counterparty_name:string|null; installment_number:number|null; installment_count:number|null; amount:number|string; source_total_amount:number|string };
type StatementRow = { statement_id:string; tenant_id:string; company_id:string; card_id:string; statement_month:string; due_date:string; statement_amount:number|string; paid_amount:number|string; remaining_amount:number|string; payment_status:CardStatementBalance['paymentStatus'] };
type PurchaseRow = { id:string; tenant_id:string; company_id:string; expense_company_id:string; card_id:string; purchase_date:string; description:string; counterparty_name:string|null; category_id:string; cost_center_id:string|null; total_amount:number|string; installment_count:number; notes:string|null };
type CreatedRow = { transaction_id:string; first_statement_month:string; committed_amount:number|string; available_limit:number|string };
type ClosedStatementRow = { statement_id:string; statement_amount:number|string; due_date:string; payment_status:ClosedCardStatement['paymentStatus'] };
type StatementPaymentRow = { payment_id:string; paid_total:number|string; remaining_amount:number|string; payment_status:RecordedCardStatementPayment['paymentStatus']; available_limit:number|string };

function toCard(row:CardRow):CreditCard { return { id:row.id, tenantId:row.tenant_id, companyId:row.company_id, name:row.name, bankInstitution:row.bank_institution, lastFour:row.last_four, creditLimit:Number(row.credit_limit), closingDay:row.closing_day, dueDay:row.due_day, defaultPaymentAccountId:row.default_payment_account_id, status:row.status, sortOrder:Number(row.sort_order) }; }
function isCardRow(value:unknown):value is CardRow { if(typeof value!=='object'||value===null)return false; const row=value as Record<string,unknown>; return typeof row.id==='string'&&typeof row.tenant_id==='string'&&typeof row.company_id==='string'&&typeof row.name==='string'; }
function isCreatedRow(value:unknown):value is CreatedRow { if(typeof value!=='object'||value===null)return false; const row=value as Record<string,unknown>; return typeof row.transaction_id==='string'&&typeof row.first_statement_month==='string'&&(typeof row.committed_amount==='number'||typeof row.committed_amount==='string')&&(typeof row.available_limit==='number'||typeof row.available_limit==='string'); }
function isClosedStatementRow(value:unknown):value is ClosedStatementRow { if(typeof value!=='object'||value===null)return false; const row=value as Record<string,unknown>; return typeof row.statement_id==='string'&&(typeof row.statement_amount==='number'||typeof row.statement_amount==='string')&&typeof row.due_date==='string'&&(row.payment_status==='pending'||row.payment_status==='partial'||row.payment_status==='paid'); }
function isStatementPaymentRow(value:unknown):value is StatementPaymentRow { if(typeof value!=='object'||value===null)return false; const row=value as Record<string,unknown>; return typeof row.payment_id==='string'&&(typeof row.paid_total==='number'||typeof row.paid_total==='string')&&(typeof row.remaining_amount==='number'||typeof row.remaining_amount==='string')&&(row.payment_status==='partial'||row.payment_status==='paid')&&(typeof row.available_limit==='number'||typeof row.available_limit==='string'); }
function requireText(value:string,field:string):string { const normalized=value.trim(); if(!normalized)throw new Error(`${field} is required`); return normalized; }
function requireIsoDate(value:string,field:string):string { if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new Error(`${field} must use YYYY-MM-DD`); return value; }
function normalizeCard(input:CreateCreditCard|UpdateCreditCard) { const name=requireText(input.name,'name'); const lastFour=input.lastFour?.trim()||null; if(lastFour!==null&&!/^\d{4}$/.test(lastFour))throw new Error('lastFour must contain exactly four digits'); if(!Number.isFinite(input.creditLimit)||input.creditLimit<0)throw new Error('creditLimit must be zero or greater'); if(!Number.isInteger(input.closingDay)||input.closingDay<1||input.closingDay>31)throw new Error('closingDay must be between 1 and 31'); if(!Number.isInteger(input.dueDay)||input.dueDay<1||input.dueDay>31)throw new Error('dueDay must be between 1 and 31'); return {...input,name,lastFour}; }

const cardColumns='id,tenant_id,company_id,name,bank_institution,last_four,credit_limit,closing_day,due_day,default_payment_account_id,status,sort_order';

export class SupabaseCardRepository implements CardRepository {
 constructor(private readonly client:SupabaseClient) {}
 async listCards(scope:CompanyScope):Promise<readonly CreditCard[]> { const {data,error}=await this.client.from('credit_cards').select(cardColumns).eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).order('sort_order',{ascending:true}).order('name').returns<CardRow[]>(); if(error)throw error; return data.map(toCard); }
 async createCard(raw:CreateCreditCard):Promise<CreditCard> { const input=normalizeCard(raw); const {data,error}=await this.client.from('credit_cards').insert({tenant_id:input.tenantId,company_id:input.companyId,name:input.name,bank_institution:input.bankInstitution??null,last_four:input.lastFour,credit_limit:input.creditLimit,closing_day:input.closingDay,due_day:input.dueDay,default_payment_account_id:input.defaultPaymentAccountId??null}).select(cardColumns).single<CardRow>(); if(error)throw error; return toCard(data); }
 async updateCard(raw:UpdateCreditCard):Promise<CreditCard> { const input=normalizeCard(raw); const sourceCompanyId=raw.sourceCompanyId??input.companyId; if(sourceCompanyId!==input.companyId){ const result=await this.client.rpc('reassign_credit_card_company',{p_tenant_id:input.tenantId,p_card_id:raw.id,p_source_company_id:sourceCompanyId,p_target_company_id:input.companyId,p_name:input.name,p_bank_institution:input.bankInstitution??'',p_last_four:input.lastFour??'',p_credit_limit:input.creditLimit,p_closing_day:input.closingDay,p_due_day:input.dueDay,p_status:raw.status}); if(result.error)throw result.error; const data:unknown=result.data; const row:unknown=Array.isArray(data)?data[0]:data; if(!isCardRow(row))throw new Error('card reassignment returned an invalid result'); return toCard(row); } const {data,error}=await this.client.from('credit_cards').update({name:input.name,bank_institution:input.bankInstitution??null,last_four:input.lastFour,credit_limit:input.creditLimit,closing_day:input.closingDay,due_day:input.dueDay,default_payment_account_id:input.defaultPaymentAccountId??null,status:raw.status}).eq('tenant_id',input.tenantId).eq('company_id',sourceCompanyId).eq('id',raw.id).select(cardColumns).single<CardRow>(); if(error)throw error; return toCard(data); }
 async reorder(tenantId:string,orderedIds:readonly string[]):Promise<void> { if(orderedIds.length<2)return; const {error}=await this.client.rpc('reorder_credit_cards',{p_tenant_id:tenantId,p_ordered_ids:[...orderedIds]}); if(error)throw error; }
 async listLimits(scope:CompanyScope):Promise<readonly CreditCardLimit[]> { const {data,error}=await this.client.from('credit_card_limits').select('card_id,tenant_id,company_id,name,credit_limit,committed_amount,available_limit,sort_order').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).order('sort_order',{ascending:true}).order('name').returns<LimitRow[]>(); if(error)throw error; return data.map(row=>({cardId:row.card_id,tenantId:row.tenant_id,companyId:row.company_id,name:row.name,creditLimit:Number(row.credit_limit),committedAmount:Number(row.committed_amount),availableLimit:Number(row.available_limit),sortOrder:Number(row.sort_order)})); }
 async listInstallments(scope:CompanyScope,cardId?:string):Promise<readonly CardInstallment[]> { let query=this.client.from('card_installments').select('id,tenant_id,company_id,card_id,transaction_id,installment_number,installment_count,statement_month,amount').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).order('statement_month').order('installment_number'); if(cardId)query=query.eq('card_id',cardId); const {data,error}=await query.returns<InstallmentRow[]>(); if(error)throw error; return data.map(row=>({id:row.id,tenantId:row.tenant_id,companyId:row.company_id,cardId:row.card_id,transactionId:row.transaction_id,installmentNumber:row.installment_number,installmentCount:row.installment_count,statementMonth:row.statement_month,amount:Number(row.amount)})); }
 async listStatementItems(scope:CompanyScope,cardId:string):Promise<readonly CardStatementItem[]> { const {data,error}=await this.client.from('finance_card_installments_operational').select('tenant_id,company_id,card_id,transaction_id,purchase_date,description,counterparty_name,installment_number,installment_count,installment_label,statement_month,amount,statement_id,due_date,statement_status').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('card_id',cardId).order('statement_month',{ascending:false}).order('purchase_date',{ascending:false}).returns<StatementItemRow[]>(); if(error)throw error; return data.map(row=>({tenantId:row.tenant_id,companyId:row.company_id,cardId:row.card_id,transactionId:row.transaction_id,purchaseDate:row.purchase_date,description:row.description,counterpartyName:row.counterparty_name,installmentNumber:row.installment_number,installmentCount:row.installment_count,installmentLabel:row.installment_label,statementMonth:row.statement_month,amount:Number(row.amount),statementId:row.statement_id,dueDate:row.due_date,statementStatus:row.statement_status})); }
 async listStatementActivities(scope:CompanyScope,cardId:string):Promise<readonly CardStatementActivity[]> { const {data,error}=await this.client.from('card_statement_activity').select('tenant_id,company_id,card_id,statement_month,activity_key,activity_type,source_id,activity_date,description,counterparty_name,installment_number,installment_count,amount,source_total_amount').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).eq('card_id',cardId).order('statement_month',{ascending:false}).order('activity_date',{ascending:false}).returns<ActivityRow[]>(); if(error)throw error; return data.map(row=>({tenantId:row.tenant_id,companyId:row.company_id,cardId:row.card_id,statementMonth:row.statement_month,activityKey:row.activity_key,activityType:row.activity_type,sourceId:row.source_id,activityDate:row.activity_date,description:row.description,counterpartyName:row.counterparty_name,installmentNumber:row.installment_number,installmentCount:row.installment_count,amount:Number(row.amount),sourceTotalAmount:Number(row.source_total_amount)})); }
 async listStatements(scope:CompanyScope,cardId?:string):Promise<readonly CardStatementBalance[]> { let query=this.client.from('credit_card_statement_balances').select('statement_id,tenant_id,company_id,card_id,statement_month,due_date,statement_amount,paid_amount,remaining_amount,payment_status').eq('tenant_id',scope.tenantId).eq('company_id',scope.companyId).order('statement_month',{ascending:false}); if(cardId)query=query.eq('card_id',cardId); const {data,error}=await query.returns<StatementRow[]>(); if(error)throw error; return data.map(row=>({statementId:row.statement_id,tenantId:row.tenant_id,companyId:row.company_id,cardId:row.card_id,statementMonth:row.statement_month,dueDate:row.due_date,statementAmount:Number(row.statement_amount),paidAmount:Number(row.paid_amount),remainingAmount:Number(row.remaining_amount),paymentStatus:row.payment_status})); }
 async createPurchase(raw:CreateCardPurchase):Promise<CreatedCardPurchase> { const input=normalizeCardPurchase(raw); const result=await this.client.rpc('create_card_purchase',{p_tenant_id:input.tenantId,p_company_id:input.companyId,p_card_id:input.cardId,p_purchase_date:input.purchaseDate,p_description:input.description,p_counterparty_name:input.counterpartyName??null,p_category_id:input.categoryId,p_cost_center_id:input.costCenterId??null,p_total_amount:input.totalAmount,p_installment_count:input.installmentCount,p_idempotency_key:input.idempotencyKey,p_notes:input.notes??null}); if(result.error)throw result.error; const data:unknown=result.data; const row:unknown=Array.isArray(data)?data[0]:data; if(!isCreatedRow(row))throw new Error('card purchase returned an invalid result'); return {transactionId:row.transaction_id,firstStatementMonth:row.first_statement_month,committedAmount:Number(row.committed_amount),availableLimit:Number(row.available_limit)}; }
 async getPurchase(input:CompanyScope & {transactionId:string}):Promise<CardPurchaseDetails> { const {data,error}=await this.client.from('card_transactions').select('id,tenant_id,company_id,expense_company_id,card_id,purchase_date,description,counterparty_name,category_id,cost_center_id,total_amount,installment_count,notes').eq('tenant_id',input.tenantId).eq('company_id',input.companyId).eq('id',input.transactionId).single<PurchaseRow>(); if(error)throw error; return {transactionId:data.id,tenantId:data.tenant_id,companyId:data.company_id,expenseCompanyId:data.expense_company_id,cardId:data.card_id,purchaseDate:data.purchase_date,description:data.description,counterpartyName:data.counterparty_name,categoryId:data.category_id,costCenterId:data.cost_center_id,totalAmount:Number(data.total_amount),installmentCount:data.installment_count,notes:data.notes}; }
 async updatePurchase(input:UpdateCardPurchase):Promise<void> { const {error}=await this.client.rpc('update_card_purchase',{p_tenant_id:input.tenantId,p_company_id:input.companyId,p_transaction_id:input.transactionId,p_card_id:input.cardId,p_expense_company_id:input.expenseCompanyId,p_purchase_date:input.purchaseDate,p_description:input.description,p_counterparty_name:input.counterpartyName??null,p_category_id:input.categoryId,p_cost_center_id:input.costCenterId??null,p_total_amount:input.totalAmount,p_installment_count:input.installmentCount,p_notes:input.notes??null}); if(error)throw error; }
 async deletePurchase(input:CompanyScope & {transactionId:string}):Promise<void> { const {error}=await this.client.rpc('delete_card_purchase',{p_tenant_id:input.tenantId,p_company_id:input.companyId,p_transaction_id:input.transactionId}); if(error)throw error; }
 async updateStatementPayment(input:CompanyScope & {paymentId:string;paidOn:string;amount:number;notes:string|null}):Promise<void> { const {error}=await this.client.rpc('update_card_statement_payment_activity',{p_tenant_id:input.tenantId,p_company_id:input.companyId,p_payment_id:input.paymentId,p_paid_on:input.paidOn,p_amount:input.amount,p_notes:input.notes}); if(error)throw error; }
 async deleteStatementPayment(input:CompanyScope & {paymentId:string}):Promise<void> { const {error}=await this.client.rpc('delete_card_statement_payment_activity',{p_tenant_id:input.tenantId,p_company_id:input.companyId,p_payment_id:input.paymentId}); if(error)throw error; }
 async closeStatement(raw:CloseCardStatement):Promise<ClosedCardStatement> { const tenantId=requireText(raw.tenantId,'tenantId'); const companyId=requireText(raw.companyId,'companyId'); const cardId=requireText(raw.cardId,'cardId'); const statementMonth=requireIsoDate(raw.statementMonth,'statementMonth'); if(!statementMonth.endsWith('-01'))throw new Error('statementMonth must be the first day of a month'); const result=await this.client.rpc('close_card_statement',{p_tenant_id:tenantId,p_company_id:companyId,p_card_id:cardId,p_statement_month:statementMonth}); if(result.error)throw result.error; const data:unknown=result.data; const row:unknown=Array.isArray(data)?data[0]:data; if(!isClosedStatementRow(row))throw new Error('card statement close returned an invalid result'); return {statementId:row.statement_id,statementAmount:Number(row.statement_amount),dueDate:row.due_date,paymentStatus:row.payment_status}; }
 async recordStatementPayment(raw:RecordCardStatementPayment):Promise<RecordedCardStatementPayment> { const tenantId=requireText(raw.tenantId,'tenantId'); const companyId=requireText(raw.companyId,'companyId'); const statementId=requireText(raw.statementId,'statementId'); const accountId=requireText(raw.accountId,'accountId'); const idempotencyKey=requireText(raw.idempotencyKey,'idempotencyKey'); const paidOn=requireIsoDate(raw.paidOn,'paidOn'); if(!Number.isFinite(raw.amount)||raw.amount<=0)throw new Error('amount must be greater than zero'); if(Math.abs(raw.amount * 100 - Math.round(raw.amount * 100)) > 1e-6)throw new Error('amount supports at most two decimal places'); const result=await this.client.rpc('record_card_statement_payment',{p_tenant_id:tenantId,p_company_id:companyId,p_statement_id:statementId,p_account_id:accountId,p_paid_on:paidOn,p_amount:raw.amount,p_idempotency_key:idempotencyKey,p_notes:raw.notes?.trim()||null}); if(result.error)throw result.error; const data:unknown=result.data; const row:unknown=Array.isArray(data)?data[0]:data; if(!isStatementPaymentRow(row))throw new Error('card statement payment returned an invalid result'); return {paymentId:row.payment_id,paidTotal:Number(row.paid_total),remainingAmount:Number(row.remaining_amount),paymentStatus:row.payment_status,availableLimit:Number(row.available_limit)}; }
}