begin;
alter table public.employee_documents add column if not exists file_path text;
alter table public.employee_documents add column if not exists file_name text;
alter table public.employee_documents add column if not exists mime_type text;
alter table public.employee_documents add column if not exists file_size_bytes bigint check(file_size_bytes is null or file_size_bytes>=0);
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('hr-documents','hr-documents',false,10485760,array['application/pdf','image/jpeg','image/png','image/webp']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists hr_documents_storage_select on storage.objects;drop policy if exists hr_documents_storage_insert on storage.objects;drop policy if exists hr_documents_storage_update on storage.objects;drop policy if exists hr_documents_storage_delete on storage.objects;
create policy hr_documents_storage_select on storage.objects for select to authenticated using(bucket_id='hr-documents' and app_private.can_access_company((storage.foldername(name))[1]::uuid,(storage.foldername(name))[2]::uuid));
create policy hr_documents_storage_insert on storage.objects for insert to authenticated with check(bucket_id='hr-documents' and app_private.can_manage_company((storage.foldername(name))[1]::uuid,(storage.foldername(name))[2]::uuid));
create policy hr_documents_storage_update on storage.objects for update to authenticated using(bucket_id='hr-documents' and app_private.can_manage_company((storage.foldername(name))[1]::uuid,(storage.foldername(name))[2]::uuid)) with check(bucket_id='hr-documents' and app_private.can_manage_company((storage.foldername(name))[1]::uuid,(storage.foldername(name))[2]::uuid));
create policy hr_documents_storage_delete on storage.objects for delete to authenticated using(bucket_id='hr-documents' and app_private.can_manage_company((storage.foldername(name))[1]::uuid,(storage.foldername(name))[2]::uuid));
commit;