import type { HrEmployeeRow } from '../application/HrOperationsRepository';
import type { AttendanceRecord, AttendanceStatus } from '../infrastructure/HrWorkspaceService';
import { Button } from '../../../shared/ui/Button';
import { Card } from '../../../shared/ui/Card';
import { Feedback } from '../../../shared/ui/Feedback';
import { Input } from '../../../shared/ui/Input';
import { Select } from '../../../shared/ui/Select';

type Employee=HrEmployeeRow&{companyId:string;companyName:string;tenantId:string};
const attendanceOptions=[{value:'',label:'Não registrado'},{value:'present',label:'Presente'},{value:'absence',label:'Falta'},{value:'medical_certificate',label:'Atestado'},{value:'vacation',label:'Férias'},{value:'day_off',label:'Folga'},{value:'other',label:'Outro'}];
export function HrAttendanceSection({date,setDate,search,setSearch,rows,employees,loading,feedback,onAllPresent,onChange}:{date:string;setDate:(v:string)=>void;search:string;setSearch:(v:string)=>void;rows:AttendanceRecord[];employees:Employee[];loading:boolean;feedback:string|null;onAllPresent:()=>void;onChange:(employee:Employee,status:AttendanceStatus)=>void}){const byContract=new Map(rows.map(row=>[row.employmentContractId,row]));return <div className="hr-workspace__content"><Card title="Presença e ponto" actions={<Button variant="secondary">Registrados {rows.length}</Button>}><div className="hr-workspace__attendance-controls"><Input label="Data" type="date" value={date} onChange={e=>setDate(e.target.value)}/><Input label="Buscar colaborador" placeholder="Digite o nome" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="hr-workspace__actions"><Button onClick={onAllPresent} disabled={loading||employees.length===0}>Marcar todos presentes</Button></div>{feedback&&<Feedback title="Presença" message={feedback} tone={feedback.includes('marcado')||feedback.includes('registrado')?'success':'info'}/>}<div className="hr-workspace__attendance-list">{loading?<p className="ui-muted">Carregando presença do dia...</p>:employees.length===0?<p className="ui-muted">Nenhum colaborador ativo para o filtro selecionado.</p>:employees.map(employee=>{const row=byContract.get(employee.employmentContractId);return <div className="hr-workspace__attendance-row" key={`${employee.companyId}:${employee.employmentContractId}`}><div><strong>{employee.fullName}</strong><span>{employee.companyName} · {employee.jobTitle} · {employee.costCenterName??'Sem obra'}</span></div><Select label="Status" value={row?.status??''} options={attendanceOptions} onChange={event=>{const status=event.target.value as AttendanceStatus;if(status)onChange(employee,status);}}/></div>;})}</div></Card></div>}
