import type { EmploymentType } from '../application/HrOperationsRepository';
import { Button } from '../../../shared/ui/Button';
import { Feedback } from '../../../shared/ui/Feedback';
import { Input } from '../../../shared/ui/Input';
import { Select } from '../../../shared/ui/Select';
export type HrEmployeeDraft={fullName:string;companyId:string;jobTitle:string;cpf:string;pix:string;phone:string;email:string;notes:string;employmentType:EmploymentType;sector:string;supervisor:string;weeklyHours:string;bankHoursEnabled:string;baseSalary:string;costCenterId:string;effectiveOn:string};
type Option={value:string;label:string};
export function HrEmployeeForm({draft,setDraft,step,setStep,feedback,companyOptions,costCenterOptions,employmentTypeOptions}:{draft:HrEmployeeDraft;setDraft:(v:HrEmployeeDraft)=>void;step:1|2;setStep:(v:1|2)=>void;feedback:string|null;companyOptions:Option[];costCenterOptions:Option[];employmentTypeOptions:Option[]}){
 const set=<K extends keyof HrEmployeeDraft>(key:K,value:HrEmployeeDraft[K])=>setDraft({...draft,[key]:value});
 return <div className="hr-employee-form"><div className="hr-employee-form__tabs"><button type="button" className={step===1?'is-active':''} onClick={()=>setStep(1)}><span>1</span>Dados e salário</button><button type="button" className={step===2?'is-active':''} onClick={()=>setStep(2)}><span>2</span>Valores e resumo</button></div>
 {feedback&&<Feedback tone="danger" title="Não foi possível cadastrar" message={feedback}/>}
 {step===1&&<div className="hr-workspace__edit-grid"><Input label="Nome" value={draft.fullName} onChange={e=>set('fullName',e.target.value)}/><Input label="CPF" value={draft.cpf} placeholder="000.000.000-00" onChange={e=>set('cpf',e.target.value)}/><Input label="Telefone" value={draft.phone} placeholder="(00) 00000-0000" onChange={e=>set('phone',e.target.value)}/><Input label="PIX" value={draft.pix} onChange={e=>set('pix',e.target.value)}/><Select label="Empresa" value={draft.companyId} options={companyOptions} onChange={e=>setDraft({...draft,companyId:e.target.value,costCenterId:''})}/><Select label="Obra / centro de custo" value={draft.costCenterId} options={costCenterOptions} onChange={e=>set('costCenterId',e.target.value)}/><Input label="Setor" value={draft.sector} onChange={e=>set('sector',e.target.value)}/><Input label="Encarregado" value={draft.supervisor} onChange={e=>set('supervisor',e.target.value)}/><Input label="Função" value={draft.jobTitle} onChange={e=>set('jobTitle',e.target.value)}/><Select label="Tipo de vínculo" value={draft.employmentType} options={employmentTypeOptions} onChange={e=>set('employmentType',e.target.value as EmploymentType)}/><Input label="Data de admissão" type="date" value={draft.effectiveOn} onChange={e=>set('effectiveOn',e.target.value)}/><Input label="E-mail" value={draft.email} onChange={e=>set('email',e.target.value)}/></div>}
 {step===2&&<div className="hr-workspace__edit-grid"><Input label="Salário de carteira" type="number" min="0" step="0.01" value={draft.baseSalary} onChange={e=>set('baseSalary',e.target.value)}/><Input label="Jornada semanal (h)" type="number" min="1" value={draft.weeklyHours} onChange={e=>set('weeklyHours',e.target.value)}/><Select label="Banco de horas" value={draft.bankHoursEnabled} options={[{value:'yes',label:'Controlar banco de horas'},{value:'no',label:'Não controlar'}]} onChange={e=>set('bankHoursEnabled',e.target.value)}/><Input label="Observações" value={draft.notes} onChange={e=>set('notes',e.target.value)}/><div className="hr-employee-form__summary hr-workspace__edit-wide"><strong>Resumo do colaborador</strong><span>{draft.fullName||'Nome não informado'} · {companyOptions.find(x=>x.value===draft.companyId)?.label||'Empresa não informada'} · {draft.jobTitle||'Função não informada'}</span></div><Button variant="secondary" onClick={()=>setStep(1)}>Voltar</Button></div>}</div>;
}