import { Clock3, FolderUp, HardHat } from 'lucide-react';
import type { HrEmployeeRow } from '../application/HrOperationsRepository';
import type { HrEpiDelivery } from '../infrastructure/HrWorkspaceService';
import { Button } from '../../../shared/ui/Button';
import { Card } from '../../../shared/ui/Card';
import { Feedback } from '../../../shared/ui/Feedback';
import { Input } from '../../../shared/ui/Input';
import { Select } from '../../../shared/ui/Select';

type Employee=HrEmployeeRow&{companyId:string;companyName:string;tenantId:string};
type Draft={employmentContractId:string;epiName:string;quantity:string;deliveredOn:string;caNumber:string;notes:string};
export function HrEpiSection({deliveries,employees,activeEmployees,draft,setDraft,saving,feedback,onRegister}:{deliveries:HrEpiDelivery[];employees:Employee[];activeEmployees:Employee[];draft:Draft;setDraft:(v:Draft)=>void;saving:boolean;feedback:string|null;onRegister:()=>void}){
 return <div className="hr-workspace__content"><div className="hr-workspace__quick-three"><Card title="Histórico de entregas"><strong>{deliveries.length}</strong></Card><Card title="Colaboradores com EPI"><strong>{new Set(deliveries.map(i=>i.employmentContractId)).size}</strong></Card><Card title="Fichas de EPIs"><FolderUp/></Card></div><Card title="Entrega de EPI"><div className="hr-workspace__form"><Select label="Colaborador" value={draft.employmentContractId} onChange={e=>setDraft({...draft,employmentContractId:e.target.value})} options={[{value:'',label:'Selecione um colaborador'},...activeEmployees.map(item=>({value:item.employmentContractId,label:`${item.fullName} · ${item.companyName}`}))]}/><Input label="EPI" placeholder="Ex.: Capacete classe B" value={draft.epiName} onChange={e=>setDraft({...draft,epiName:e.target.value})}/><Input label="Quantidade" type="number" min="1" value={draft.quantity} onChange={e=>setDraft({...draft,quantity:e.target.value})}/><Input label="Data da entrega" type="date" value={draft.deliveredOn} onChange={e=>setDraft({...draft,deliveredOn:e.target.value})}/><Input label="CA" placeholder="Número do CA" value={draft.caNumber} onChange={e=>setDraft({...draft,caNumber:e.target.value})}/><Input label="Observações" value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/><Button onClick={onRegister} disabled={saving}>{saving?'Registrando...':'Registrar entrega'}</Button>{feedback&&<Feedback title="EPI" message={feedback} tone={feedback.includes('sucesso')?'success':'danger'}/>}</div></Card><Card title="Histórico de entregas">{deliveries.length===0?<p className="ui-muted">Nenhuma entrega registrada.</p>:<div className="hr-workspace__list">{deliveries.map(item=>{const employee=employees.find(e=>e.employmentContractId===item.employmentContractId);return <div className="hr-workspace__employee-row" key={item.id}><div><strong>{employee?.fullName??'Colaborador'}</strong><span>{item.epiName} · Qtd. {item.quantity}{item.caNumber?` · CA ${item.caNumber}`:''}</span></div><div><strong>{new Date(`${item.deliveredOn}T12:00:00`).toLocaleDateString('pt-BR')}</strong><span>{employee?.companyName??''}</span></div></div>;})}</div>}</Card></div>;
}
