import type { FixedCompensationItem } from '../application/HrOperationsRepository';
import { Button } from '../../../shared/ui/Button';
import { Input } from '../../../shared/ui/Input';
import { Select } from '../../../shared/ui/Select';

export function HrFixedCompensationEditor({items,setItems,description,setDescription,valueText,setValueText,kind,setKind,employmentContractId,baseSalary,money}:{items:FixedCompensationItem[];setItems:(items:FixedCompensationItem[])=>void;description:string;setDescription:(value:string)=>void;valueText:string;setValueText:(value:string)=>void;kind:'earning'|'deduction';setKind:(value:'earning'|'deduction')=>void;employmentContractId:string;baseSalary:number;money:Intl.NumberFormat}){
 const amount=(item:FixedCompensationItem)=>item.valueType==='percent'?baseSalary*item.value/100:item.value;
 const add=()=>{const value=Number(valueText);if(!description.trim()||!Number.isFinite(value)||value<=0)return;setItems([...items,{id:'new-'+Date.now(),employmentContractId,description:description.trim(),kind,destination:'payment',valueType:'fixed',value,recurring:true,active:true,affectsInss:false,affectsIrrf:false,affectsFgts:false}]);setDescription('');setValueText('');};
 return <div className="hr-workspace__edit-wide hr-fixed-comp"><strong>Composição salarial fixa</strong><small>Acréscimos e descontos recorrentes, separados do salário de carteira.</small><div className="hr-fixed-comp__form"><Input label="Descrição" value={description} placeholder="Ex.: Extra mensal" onChange={e=>setDescription(e.target.value)}/><Select label="Tipo" value={kind} options={[{value:'earning',label:'Acréscimo'},{value:'deduction',label:'Desconto'}]} onChange={e=>setKind(e.target.value as 'earning'|'deduction')}/><Input label="Valor" type="number" min="0" step="0.01" value={valueText} onChange={e=>setValueText(e.target.value)}/><Button type="button" size="sm" onClick={add}>Adicionar fixo</Button></div><div className="hr-fixed-comp__list">{items.map(item=><div key={item.id}><span>{item.description}</span><strong>{item.kind==='deduction'?'- ':'+ '}{money.format(amount(item))}</strong><Button type="button" size="sm" variant="secondary" onClick={()=>setItems(items.filter(x=>x.id!==item.id))}>Remover</Button></div>)}{items.length===0&&<span className="ui-muted">Nenhum valor fixo cadastrado.</span>}</div></div>;
}
