import { useEffect, useMemo, useState } from 'react';
import { BarChart3, CalendarCheck, Clock3, FileText, FolderUp, HardHat, ReceiptText, ShieldCheck, Upload, UsersRound, WalletCards } from 'lucide-react';
import type { CompanySummary } from '../../platform/domain/AccessContext';
import type { EmploymentType, HrEmployeeRow, HrOperationalSnapshot } from '../application/HrOperationsRepository';
import { getHrBudgetRepository, getHrOperationsRepository } from '../infrastructure/createHrRepositories';
import { listAttendanceForDate, saveAttendance, saveAttendanceBatch, saveAttendancePeriod, transferEmployeeCompany, type AttendanceRecord, type AttendanceStatus } from '../infrastructure/HrWorkspaceService';
import { Button } from '../../../shared/ui/Button';
import { Card } from '../../../shared/ui/Card';
import { Dialog } from '../../../shared/ui/Dialog';
import { Feedback } from '../../../shared/ui/Feedback';
import { Input } from '../../../shared/ui/Input';
import { SearchableSelect, type SearchableSelectOption } from '../../../shared/ui/SearchableSelect';
import { Select } from '../../../shared/ui/Select';
import { currentHrCompetence } from './useHrBudgetOverview';
import './hr-workspace.css';

type HrWorkspaceTab = 'dashboard' | 'colaboradores' | 'epis' | 'compliance' | 'salarios' | 'presenca' | 'banco_horas' | 'fechamento' | 'relatorios' | 'recibos' | 'importacoes' | 'documentos';
type CompanyData = { company: CompanySummary; operations: HrOperationalSnapshot; overview: Awaited<ReturnType<ReturnType<typeof getHrBudgetRepository>['getOverview']>>; };
type WorkspaceEmployee = HrEmployeeRow & { companyId: string; companyName: string; tenantId: string };
type EmployeeDraft = {
  fullName: string;
  companyId: string;
  jobTitle: string;
  cpf: string;
  pix: string;
  phone: string;
  email: string;
  notes: string;
  employmentType: EmploymentType;
  sector: string;
  supervisor: string;
  weeklyHours: string;
  bankHoursEnabled: string;
  baseSalary: string;
  costCenterId: string;
  effectiveOn: string;
};
type AttendancePeriodDraft = {
  employee: WorkspaceEmployee;
  status: 'medical_certificate' | 'vacation';
  startDate: string;
  endDate: string;
  days: string;
  notes: string;
};

const ALL_HR_COMPANIES = '__all_hr_companies__';
const tabs: Array<{ id: HrWorkspaceTab; label: string; icon: typeof BarChart3 }> = [
  { id:'dashboard',label:'Dashboard',icon:BarChart3 },{ id:'colaboradores',label:'Colaboradores',icon:UsersRound },{ id:'epis',label:'EPIs',icon:HardHat },{ id:'compliance',label:'ASO, NR e Férias',icon:ShieldCheck },{ id:'salarios',label:'Salários e pagamentos',icon:WalletCards },{ id:'presenca',label:'Presença e ponto',icon:CalendarCheck },{ id:'banco_horas',label:'Banco de horas',icon:Clock3 },{ id:'fechamento',label:'Fechamento quinzenal',icon:WalletCards },{ id:'relatorios',label:'Relatórios',icon:FileText },{ id:'recibos',label:'Recibos',icon:ReceiptText },{ id:'importacoes',label:'Importações',icon:Upload },{ id:'documentos',label:'Importações RH',icon:FolderUp },
];
const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const employmentTypeOptions = [
  { value:'clt',label:'CLT' },{ value:'pj',label:'PJ' },{ value:'autonomo',label:'Autônomo' },{ value:'temporario',label:'Temporário' },{ value:'estagio',label:'Estágio' },{ value:'prestador',label:'Prestador' },{ value:'outro',label:'Outro' },
];
const attendanceOptions = [
  { value:'',label:'Não registrado' },{ value:'present',label:'Presente' },{ value:'absence',label:'Falta' },{ value:'medical_certificate',label:'Atestado' },{ value:'vacation',label:'Férias' },{ value:'day_off',label:'Folga' },{ value:'other',label:'Outro' },
];
function companyLabel(company: CompanySummary): string { const raw=`${company.tradeName??''} ${company.legalName}`.toLocaleUpperCase('pt-BR'); if(raw.includes('PESSOAL'))return'Pessoal'; if(raw.includes('PR-HIST')||/(^|\s)PR(\s|$)/.test(raw))return'PR'; if(raw.includes('CR-HIST')||/(^|\s)CR(\s|$)/.test(raw))return'CR'; return company.tradeName??company.legalName; }
function normalizeSearch(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR').trim();}
function smartMatches(values:Array<string|null|undefined>,query:string){const q=normalizeSearch(query);if(!q)return true;const tokens=q.split(/\s+/).filter(Boolean);const searchable=normalizeSearch(values.filter(Boolean).join(' '));const words=searchable.split(/\s+/).filter(Boolean);return tokens.every(t=>words.some(w=>w.startsWith(t))||searchable.includes(t));}
function localToday(){const date=new Date();return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function addDays(value:string,days:number){const date=new Date(`${value}T12:00:00`);date.setDate(date.getDate()+days);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function messageFrom(error: unknown){return error instanceof Error&&error.message?error.message:'Não foi possível concluir a operação.';}

export function HrWorkspacePage({companies,initialCompanyId}:{companies:readonly CompanySummary[];initialCompanyId?:string}){
 const requestedTab=new URLSearchParams(window.location.search).get('tab');
 const [tab,setTab]=useState<HrWorkspaceTab>(()=>tabs.some(item=>item.id===requestedTab)?requestedTab as HrWorkspaceTab:'dashboard');
 const [competence,setCompetence]=useState(()=>currentHrCompetence().month.slice(0,7));
 const [companyFilter,setCompanyFilter]=useState(()=>initialCompanyId&&companies.some(i=>i.id===initialCompanyId)?initialCompanyId:ALL_HR_COMPANIES);
 const [employeeSearch,setEmployeeSearch]=useState(''); const [employeeStatus,setEmployeeStatus]=useState('active');
 const [companyData,setCompanyData]=useState<CompanyData[]>([]); const [loading,setLoading]=useState(false); const [errorMessage,setErrorMessage]=useState<string|null>(null); const [refreshToken,setRefreshToken]=useState(0);
 const [editingEmployee,setEditingEmployee]=useState<WorkspaceEmployee|null>(null); const [employeeDraft,setEmployeeDraft]=useState<EmployeeDraft|null>(null); const [savingEmployee,setSavingEmployee]=useState(false); const [employeeFeedback,setEmployeeFeedback]=useState<string|null>(null); const [creatingEmployee,setCreatingEmployee]=useState(false); const [newEmployeeDraft,setNewEmployeeDraft]=useState<EmployeeDraft|null>(null);
 const [attendanceDate,setAttendanceDate]=useState(localToday); const [attendance,setAttendance]=useState<AttendanceRecord[]>([]); const [attendanceLoading,setAttendanceLoading]=useState(false); const [attendanceFeedback,setAttendanceFeedback]=useState<string|null>(null); const [attendanceSearch,setAttendanceSearch]=useState('');
 const [attendancePeriod,setAttendancePeriod]=useState<AttendancePeriodDraft|null>(null); const [attendancePeriodSaving,setAttendancePeriodSaving]=useState(false);
 const competenceMonth=`${competence}-01`;
 useEffect(()=>{if(initialCompanyId&&companies.some(i=>i.id===initialCompanyId))setCompanyFilter(initialCompanyId);else if(initialCompanyId===undefined)setCompanyFilter(ALL_HR_COMPANIES);},[companies,initialCompanyId]);
 const visibleCompanies=useMemo(()=>companyFilter===ALL_HR_COMPANIES?companies:companies.filter(i=>i.id===companyFilter),[companies,companyFilter]);
 useEffect(()=>{let cancelled=false;const operationsRepository=getHrOperationsRepository();const budgetRepository=getHrBudgetRepository();setLoading(true);setErrorMessage(null);void Promise.all(visibleCompanies.map(async company=>{const scope={tenantId:company.tenantId,companyId:company.id};const [operations,overview]=await Promise.all([operationsRepository.getSnapshot(scope,competenceMonth),budgetRepository.getOverview({...scope,competenceMonth,year:Number(competenceMonth.slice(0,4))})]);return{company,operations,overview} satisfies CompanyData;})).then(data=>{if(!cancelled)setCompanyData(data);}).catch(()=>{if(!cancelled){setCompanyData([]);setErrorMessage('Não foi possível carregar os dados do RH para o filtro selecionado.');}}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[visibleCompanies,competenceMonth,refreshToken]);
 const employees: WorkspaceEmployee[]=companyData.flatMap(({company,operations})=>operations.employees.map(item=>({...item,tenantId:company.tenantId,companyId:company.id,companyName:companyLabel(company)})));
 const activeEmployees=employees.filter(i=>i.contractStatus==='active');
 const filteredEmployees=employees.filter(item=>{if(employeeStatus!=='all'&&item.contractStatus!==employeeStatus)return false;return smartMatches([item.fullName,item.jobTitle,item.costCenterName,item.cpf,item.sector,item.companyName],employeeSearch);});
 const salaryPlanned=companyData.reduce((t,i)=>t+i.overview.salaryProjection.reduce((s,r)=>s+r.plannedSalary,0),0); const salaryRealized=companyData.reduce((t,i)=>t+i.overview.salaryProjection.reduce((s,r)=>s+r.realizedSalary,0),0); const works=new Set(activeEmployees.map(i=>normalizeSearch(i.costCenterName??'')).filter(Boolean)).size; const bankHours=activeEmployees.filter(i=>i.bankHoursEnabled).length; const eventTotal=companyData.reduce((t,i)=>t+i.operations.payrollEvents.filter(e=>e.status==='active').reduce((s,e)=>s+e.amount,0),0);
 const companyOptions=[...(companies.length>1?[{value:ALL_HR_COMPANIES,label:'Todas as empresas'}]:[]),...companies.map(c=>({value:c.id,label:companyLabel(c)}))]; const editCompanyOptions=companies.map(c=>({value:c.id,label:companyLabel(c)})); const scopeLabel=companyFilter===ALL_HR_COMPANIES?'Todas as empresas':companyLabel(companies.find(i=>i.id===companyFilter)??companies[0]!);
 const employeeOptions:SearchableSelectOption[]=activeEmployees.map(item=>({value:item.employmentContractId,label:companyFilter===ALL_HR_COMPANIES?`${item.fullName} · ${item.companyName}`:item.fullName,keywords:[item.fullName,item.companyName,item.jobTitle,item.costCenterName??'',item.cpf??'',item.sector??'']})); const employeePicker=(label='Colaborador')=><SearchableSelect label={label} options={employeeOptions} placeholder="Digite o nome do colaborador"/>;
 const attendanceByContract=useMemo(()=>new Map(attendance.map(row=>[row.employmentContractId,row])),[attendance]);
 const attendanceEmployees=activeEmployees.filter(item=>smartMatches([item.fullName,item.companyName,item.jobTitle,item.costCenterName,item.cpf],attendanceSearch));
 const selectedEditCompanyData=employeeDraft?companyData.find(item=>item.company.id===employeeDraft.companyId):undefined;
 const editCostCenterOptions=[{value:'',label:'Sem obra / centro de custo'},...(selectedEditCompanyData?.operations.costCenters.filter(item=>item.status==='active').map(item=>({value:item.id,label:item.name}))??[])];

 useEffect(()=>{if(tab!=='presenca')return;let cancelled=false;setAttendanceLoading(true);setAttendanceFeedback(null);const scopes=visibleCompanies.map(company=>({tenantId:company.tenantId,companyId:company.id}));void listAttendanceForDate(scopes,attendanceDate).then(rows=>{if(!cancelled)setAttendance(rows);}).catch(error=>{if(!cancelled){setAttendance([]);setAttendanceFeedback(messageFrom(error));}}).finally(()=>{if(!cancelled)setAttendanceLoading(false);});return()=>{cancelled=true;};},[tab,visibleCompanies,attendanceDate,refreshToken]);

 function openNewEmployee(){setEmployeeFeedback(null);setNewEmployeeDraft({fullName:'',companyId:companyFilter!==ALL_HR_COMPANIES?companyFilter:(companies[0]?.id??''),jobTitle:'',cpf:'',pix:'',phone:'',email:'',notes:'',employmentType:'clt',sector:'',supervisor:'',weeklyHours:'44',bankHoursEnabled:'no',baseSalary:'0',costCenterId:'',effectiveOn:competenceMonth});setCreatingEmployee(true);}
 async function saveNewEmployee(){if(!newEmployeeDraft)return;setSavingEmployee(true);setEmployeeFeedback(null);try{const company=companies.find(item=>item.id===newEmployeeDraft.companyId);if(!company)throw new Error('Selecione a empresa do colaborador.');if(!newEmployeeDraft.fullName.trim())throw new Error('Informe o nome do colaborador.');if(!newEmployeeDraft.jobTitle.trim())throw new Error('Informe a função.');const salary=Number(newEmployeeDraft.baseSalary);if(!Number.isFinite(salary)||salary<0)throw new Error('Informe um salário válido.');await getHrOperationsRepository().createEmployeeBundle({tenantId:company.tenantId,companyId:company.id,fullName:newEmployeeDraft.fullName.trim(),jobTitle:newEmployeeDraft.jobTitle.trim(),cpf:newEmployeeDraft.cpf||null,pix:newEmployeeDraft.pix||null,phone:newEmployeeDraft.phone||null,email:newEmployeeDraft.email||null,notes:newEmployeeDraft.notes||null,employmentType:newEmployeeDraft.employmentType,sector:newEmployeeDraft.sector||null,supervisor:newEmployeeDraft.supervisor||null,weeklyHours:Number(newEmployeeDraft.weeklyHours)||44,bankHoursEnabled:newEmployeeDraft.bankHoursEnabled==='yes',hiredOn:newEmployeeDraft.effectiveOn||competenceMonth,baseSalary:salary,costCenterId:newEmployeeDraft.costCenterId||null,allocationPercent:100});setCreatingEmployee(false);setNewEmployeeDraft(null);setRefreshToken(value=>value+1);}catch(error){setEmployeeFeedback(messageFrom(error));}finally{setSavingEmployee(false);}}
 function openEmployee(employee:WorkspaceEmployee){setEditingEmployee(employee);setEmployeeFeedback(null);setEmployeeDraft({fullName:employee.fullName,companyId:employee.companyId,jobTitle:employee.jobTitle,cpf:employee.cpf??'',pix:employee.pix??'',phone:employee.phone??'',email:employee.email??'',notes:employee.notes??'',employmentType:employee.employmentType,sector:employee.sector??'',supervisor:employee.supervisor??'',weeklyHours:String(employee.weeklyHours),bankHoursEnabled:employee.bankHoursEnabled?'yes':'no',baseSalary:String(employee.baseSalary),costCenterId:employee.costCenterId??'',effectiveOn:competenceMonth});}
 async function saveEmployeeEdit(){if(!editingEmployee||!employeeDraft)return;setSavingEmployee(true);setEmployeeFeedback(null);const repository=getHrOperationsRepository();try{const sourceScope={tenantId:editingEmployee.tenantId,companyId:editingEmployee.companyId};await repository.updateEmployeeProfile(sourceScope,editingEmployee.employmentContractId,{fullName:employeeDraft.fullName,jobTitle:employeeDraft.jobTitle,cpf:employeeDraft.cpf||null,pix:employeeDraft.pix||null,phone:employeeDraft.phone||null,email:employeeDraft.email||null,notes:employeeDraft.notes||null,employmentType:employeeDraft.employmentType,sector:employeeDraft.sector||null,supervisor:employeeDraft.supervisor||null,weeklyHours:Number(employeeDraft.weeklyHours)||44,bankHoursEnabled:employeeDraft.bankHoursEnabled==='yes'});let targetContractId=editingEmployee.employmentContractId;let targetScope=sourceScope;if(employeeDraft.companyId!==editingEmployee.companyId){targetContractId=await transferEmployeeCompany({tenantId:editingEmployee.tenantId,sourceCompanyId:editingEmployee.companyId,targetCompanyId:employeeDraft.companyId,employmentContractId:editingEmployee.employmentContractId,effectiveOn:employeeDraft.effectiveOn,targetCostCenterId:employeeDraft.costCenterId||null});targetScope={tenantId:editingEmployee.tenantId,companyId:employeeDraft.companyId};}else if(employeeDraft.costCenterId&&employeeDraft.costCenterId!==editingEmployee.costCenterId){await repository.changeAllocation(sourceScope,editingEmployee.employmentContractId,employeeDraft.effectiveOn,employeeDraft.costCenterId,100);}const salary=Number(employeeDraft.baseSalary);if(Number.isFinite(salary)&&salary>=0&&salary!==editingEmployee.baseSalary){await repository.changeSalary(targetScope,targetContractId,employeeDraft.effectiveOn,salary);}setEditingEmployee(null);setEmployeeDraft(null);setRefreshToken(value=>value+1);}catch(error){setEmployeeFeedback(messageFrom(error));}finally{setSavingEmployee(false);}}
 function openAttendancePeriod(employee:WorkspaceEmployee,status:'medical_certificate'|'vacation'){setAttendanceFeedback(null);setAttendancePeriod({employee,status,startDate:attendanceDate,endDate:status==='vacation'?addDays(attendanceDate,29):attendanceDate,days:status==='vacation'?'30':'1',notes:''});}
 async function saveAttendancePeriodDraft(){if(!attendancePeriod)return;setAttendancePeriodSaving(true);setAttendanceFeedback(null);try{const days=Math.max(1,Number(attendancePeriod.days)||1);const endDate=attendancePeriod.status==='medical_certificate'?addDays(attendancePeriod.startDate,days-1):attendancePeriod.endDate;if(endDate<attendancePeriod.startDate)throw new Error('A data final não pode ser anterior à data inicial.');await saveAttendancePeriod({tenantId:attendancePeriod.employee.tenantId,companyId:attendancePeriod.employee.companyId,employmentContractId:attendancePeriod.employee.employmentContractId,startDate:attendancePeriod.startDate,endDate,status:attendancePeriod.status,notes:attendancePeriod.notes||null});const rows=await listAttendanceForDate(visibleCompanies.map(company=>({tenantId:company.tenantId,companyId:company.id})),attendanceDate);setAttendance(rows);setAttendanceFeedback(`${attendancePeriod.status==='medical_certificate'?'Atestado':'Férias'} de ${attendancePeriod.employee.fullName} registrado de ${attendancePeriod.startDate.split('-').reverse().join('/')} a ${endDate.split('-').reverse().join('/')}.`);setAttendancePeriod(null);}catch(error){setAttendanceFeedback(messageFrom(error));}finally{setAttendancePeriodSaving(false);}}
 async function changeAttendance(employee:WorkspaceEmployee,status:AttendanceStatus){if(status==='medical_certificate'||status==='vacation'){openAttendancePeriod(employee,status);return;}setAttendanceFeedback(null);try{await saveAttendance({tenantId:employee.tenantId,companyId:employee.companyId,employmentContractId:employee.employmentContractId,attendanceDate,status});const rows=await listAttendanceForDate(visibleCompanies.map(company=>({tenantId:company.tenantId,companyId:company.id})),attendanceDate);setAttendance(rows);}catch(error){setAttendanceFeedback(messageFrom(error));}}
 async function markAllPresent(){setAttendanceFeedback(null);const pending=attendanceEmployees.filter(employee=>!attendanceByContract.has(employee.employmentContractId));if(pending.length===0){setAttendanceFeedback('Todos os colaboradores exibidos já possuem registro nesta data.');return;}try{await saveAttendanceBatch(pending.map(employee=>({tenantId:employee.tenantId,companyId:employee.companyId,employmentContractId:employee.employmentContractId,attendanceDate,status:'present' as const})));const rows=await listAttendanceForDate(visibleCompanies.map(company=>({tenantId:company.tenantId,companyId:company.id})),attendanceDate);setAttendance(rows);setAttendanceFeedback(`${pending.length} colaborador(es) marcado(s) como presente.`);}catch(error){setAttendanceFeedback(messageFrom(error));}}

 return <section className="hr-workspace">
  <Card className="hr-workspace__hero" title="RH" actions={<Button size="sm" onClick={openNewEmployee}>＋ Novo colaborador</Button>}><div className="hr-workspace__top-filters"><Select label="Empresa" value={companyFilter} options={companyOptions} onChange={e=>setCompanyFilter(e.target.value)}/><Input label="Competência" type="month" value={competence} onChange={e=>setCompetence(e.target.value)}/></div></Card>
  <nav className="hr-workspace__tabs" aria-label="Módulos do RH">{tabs.map(({id,label,icon:Icon})=><button key={id} type="button" className={tab===id?'is-active':''} onClick={()=>setTab(id)}><Icon size={20}/><span>{label}</span></button>)}</nav>
  {loading&&<Card><p className="ui-muted">Carregando dados do RH...</p></Card>}{errorMessage&&<Card><Feedback tone="danger" title="Erro ao carregar RH" message={errorMessage}/></Card>}
  {!loading&&!errorMessage&&tab==='dashboard'&&<div className="hr-workspace__content"><Card title="Painel financeiro do RH" description={`${activeEmployees.length} colaboradores ativos · ${scopeLabel}`}><div className="hr-workspace__primary-total"><span>Total da competência</span><strong>{money.format(salaryRealized)}</strong><small>Previsto {money.format(salaryPlanned)}</small></div></Card><div className="hr-workspace__kpis"><Card title="Colaboradores ativos"><strong>{activeEmployees.length}</strong><span className="ui-muted">Base disponível para lançamentos</span></Card><Card title="Pagamentos"><strong>{money.format(salaryRealized)}</strong><span className="ui-muted">Competência atual</span></Card><Card title="Extras e reembolsos"><strong>{money.format(eventTotal)}</strong><span className="ui-muted">Eventos ativos</span></Card><Card title="Média por colaborador"><strong>{money.format(activeEmployees.length?salaryRealized/activeEmployees.length:0)}</strong><span className="ui-muted">Valor realizado</span></Card></div></div>}
  {!loading&&!errorMessage&&tab==='colaboradores'&&<div className="hr-workspace__content"><Card title="Colaboradores"><div className="hr-workspace__kpis hr-workspace__kpis--small"><Card title="Total"><strong>{employees.length}</strong></Card><Card title="Ativos"><strong>{activeEmployees.length}</strong></Card><Card title="Obras"><strong>{works}</strong></Card><Card title="Banco de horas"><strong>{bankHours}</strong></Card></div></Card><Card><div className="hr-workspace__filters"><Input label="Buscar colaborador" placeholder="Digite nome, CPF, empresa ou obra" value={employeeSearch} onChange={e=>setEmployeeSearch(e.target.value)}/><Select label="Status" value={employeeStatus} onChange={e=>setEmployeeStatus(e.target.value)} options={[{value:'active',label:'Ativos'},{value:'terminated',label:'Desligados'},{value:'all',label:'Todos'}]}/></div>{filteredEmployees.length===0?<p className="ui-muted">Nenhum colaborador encontrado.</p>:<div className="hr-workspace__list">{filteredEmployees.map(item=><button type="button" className="hr-workspace__employee-row" key={`${item.companyId}:${item.employmentContractId}`} onClick={()=>openEmployee(item)}><div><strong>{item.fullName}</strong><span>{item.companyName} · {item.jobTitle} · {item.costCenterName??'Sem obra'}</span></div><div><strong>{money.format(item.baseSalary)}</strong><span>{item.contractStatus==='active'?'Ativo':'Desligado'} · Editar</span></div></button>)}</div>}</Card></div>}
  {!loading&&!errorMessage&&tab==='epis'&&<div className="hr-workspace__content"><div className="hr-workspace__quick-three"><Card title="Histórico de entregas"><Clock3/></Card><Card title="Cadastro de EPIs"><HardHat/></Card><Card title="Fichas de EPIs"><FolderUp/></Card></div><Card title="Entrega de EPI"><div className="hr-workspace__form">{employeePicker()}<Input label="EPI" placeholder="Selecione ou informe o EPI"/><Input label="Quantidade" type="number" min="1" defaultValue="1"/><Input label="Data da entrega" type="date" defaultValue={localToday()}/><Button>Registrar entrega</Button></div></Card></div>}
  {!loading&&!errorMessage&&tab==='compliance'&&<div className="hr-workspace__content"><Card title="Saúde, segurança e férias" actions={<Button>＋ Novo registro</Button>}><div className="hr-workspace__segment"><Button variant="secondary">ASO</Button><Button variant="secondary">NRs e treinamentos</Button><Button variant="secondary">Férias</Button></div><div className="hr-workspace__empty">Nenhum registro nesta área.</div></Card></div>}
  {!loading&&!errorMessage&&tab==='salarios'&&<div className="hr-workspace__content"><Card title="Salário e Contas a Pagar"><div className="hr-workspace__form">{employeePicker()}<Input label="Salário / valor" value={salaryPlanned?String(salaryPlanned):''} readOnly/><div className="hr-workspace__actions"><Button>Gerar pagamento</Button><Button variant="secondary">Configurar encargos</Button></div></div></Card></div>}
  {!loading&&!errorMessage&&tab==='presenca'&&<div className="hr-workspace__content"><Card title="Presença e ponto" actions={<Button variant="secondary">Registrados {attendance.length}</Button>}><div className="hr-workspace__attendance-controls"><Input label="Data" type="date" value={attendanceDate} onChange={e=>setAttendanceDate(e.target.value)}/><Input label="Buscar colaborador" placeholder="Digite o nome" value={attendanceSearch} onChange={e=>setAttendanceSearch(e.target.value)}/></div><div className="hr-workspace__actions"><Button onClick={()=>void markAllPresent()} disabled={attendanceLoading||attendanceEmployees.length===0}>Marcar todos presentes</Button><Button variant="secondary">PDF empresa</Button></div>{attendanceFeedback&&<Feedback title="Presença" message={attendanceFeedback} tone={attendanceFeedback.includes('marcado')||attendanceFeedback.includes('registrado')?'success':'info'}/>}<div className="hr-workspace__attendance-list">{attendanceLoading?<p className="ui-muted">Carregando presença do dia...</p>:attendanceEmployees.length===0?<p className="ui-muted">Nenhum colaborador ativo para o filtro selecionado.</p>:attendanceEmployees.map(employee=>{const row=attendanceByContract.get(employee.employmentContractId);return <div className="hr-workspace__attendance-row" key={`${employee.companyId}:${employee.employmentContractId}`}><div><strong>{employee.fullName}</strong><span>{employee.companyName} · {employee.jobTitle} · {employee.costCenterName??'Sem obra'}</span></div><Select label="Status" value={row?.status??''} options={attendanceOptions} onChange={event=>{const status=event.target.value as AttendanceStatus;if(status)void changeAttendance(employee,status);}}/></div>;})}</div><div className="hr-workspace__attendance-report">{employeePicker('Relatório individual')}</div></Card></div>}
  {!loading&&!errorMessage&&tab==='banco_horas'&&<div className="hr-workspace__content"><Card title="Banco de horas"><div className="hr-workspace__form">{employeePicker()}<div className="hr-workspace__actions"><Button>Registrar movimento</Button><Button variant="secondary">Fechar competência</Button></div></div></Card></div>}
  {!loading&&!errorMessage&&tab==='fechamento'&&<div className="hr-workspace__content"><Card title="Fechamento quinzenal"><div className="hr-workspace__form"><Select label="Quinzena" options={[{value:'1',label:'1ª quinzena'},{value:'2',label:'2ª quinzena'}]}/>{employeePicker()}<div className="hr-workspace__actions"><Button>Apurar</Button><Button variant="secondary">Fechar quinzena</Button></div></div></Card></div>}
  {!loading&&!errorMessage&&tab==='relatorios'&&<div className="hr-workspace__content"><Card title="Relatórios do RH"><div className="hr-workspace__form"><Select label="Modelo" options={[{value:'detalhado',label:'Relatório detalhado por colaborador'},{value:'consolidado',label:'Consolidado por empresa'},{value:'banco',label:'Banco de horas'}]}/><Input label="Competência inicial" type="month" value={competence} onChange={e=>setCompetence(e.target.value)}/><Input label="Competência final" type="month" value={competence} readOnly/><Button>Gerar relatório</Button></div></Card></div>}
  {!loading&&!errorMessage&&tab==='recibos'&&<div className="hr-workspace__content"><Card title="Recibos" description="Selecione colaborador e verbas para gerar ou imprimir."><div className="hr-workspace__form"><Select label="Quinzena" options={[{value:'all',label:'Todas'},{value:'1',label:'1ª quinzena'},{value:'2',label:'2ª quinzena'}]}/>{employeePicker()}<div className="hr-workspace__actions"><Button>Gerar recibo</Button><Button variant="secondary">Imprimir</Button></div></div></Card></div>}
  {!loading&&!errorMessage&&tab==='importacoes'&&<div className="hr-workspace__content"><Card title="Importação" description="Modelos CSV separados por ponto e vírgula."><div className="hr-workspace__upload"><label>Importar colaboradores<input type="file" accept=".csv,text/csv"/></label><label>Importar fechamento quinzenal<input type="file" accept=".csv,text/csv"/></label><label>Importar banco de horas<input type="file" accept=".csv,text/csv"/></label></div></Card></div>}
  {!loading&&!errorMessage&&tab==='documentos'&&<div className="hr-workspace__content"><Card title="Importações RH" description="Holerites e documentos separados por módulo"><div className="hr-workspace__form"><label className="hr-workspace__file">Escolher arquivo<input type="file"/></label><Button>Importar documento RH</Button><p className="ui-muted">Nenhum documento RH importado.</p></div></Card></div>}

  <Dialog open={Boolean(creatingEmployee&&newEmployeeDraft)} title="Novo colaborador" description="Cadastre o colaborador e, se necessário, já vincule a obra/centro de custo." loading={savingEmployee} onClose={()=>{if(!savingEmployee){setCreatingEmployee(false);setNewEmployeeDraft(null);setEmployeeFeedback(null);}}} onConfirm={()=>void saveNewEmployee()} confirmLabel="Cadastrar colaborador">
   {newEmployeeDraft&&<div className="hr-workspace__edit-grid">
    {employeeFeedback&&<div className="hr-workspace__edit-wide"><Feedback tone="danger" title="Não foi possível cadastrar" message={employeeFeedback}/></div>}
    <Select label="Empresa" value={newEmployeeDraft.companyId} options={editCompanyOptions} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,companyId:e.target.value,costCenterId:''})}/>
    <Input label="Nome completo" value={newEmployeeDraft.fullName} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,fullName:e.target.value})}/>
    <Input label="Função" value={newEmployeeDraft.jobTitle} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,jobTitle:e.target.value})}/>
    <Select label="Tipo de vínculo" value={newEmployeeDraft.employmentType} options={employmentTypeOptions} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,employmentType:e.target.value as EmploymentType})}/>
    <Input label="CPF" value={newEmployeeDraft.cpf} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,cpf:e.target.value})}/><Input label="Telefone" value={newEmployeeDraft.phone} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,phone:e.target.value})}/><Input label="E-mail" value={newEmployeeDraft.email} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,email:e.target.value})}/><Input label="PIX" value={newEmployeeDraft.pix} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,pix:e.target.value})}/>
    <Input label="Data de admissão" type="date" value={newEmployeeDraft.effectiveOn} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,effectiveOn:e.target.value})}/><Input label="Salário" type="number" min="0" step="0.01" value={newEmployeeDraft.baseSalary} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,baseSalary:e.target.value})}/><Input label="Jornada semanal" type="number" min="1" value={newEmployeeDraft.weeklyHours} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,weeklyHours:e.target.value})}/>
    <Select label="Banco de horas" value={newEmployeeDraft.bankHoursEnabled} options={[{value:'yes',label:'Ativo'},{value:'no',label:'Inativo'}]} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,bankHoursEnabled:e.target.value})}/>
    <Select label="Obra / centro de custo" value={newEmployeeDraft.costCenterId} options={[{value:'',label:'Sem obra / centro de custo'},...(companyData.find(item=>item.company.id===newEmployeeDraft.companyId)?.operations.costCenters.filter(item=>item.status==='active').map(item=>({value:item.id,label:item.name}))??[])]} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,costCenterId:e.target.value})}/>
    <Input label="Setor" value={newEmployeeDraft.sector} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,sector:e.target.value})}/><Input label="Encarregado" value={newEmployeeDraft.supervisor} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,supervisor:e.target.value})}/><Input label="Observações" value={newEmployeeDraft.notes} onChange={e=>setNewEmployeeDraft({...newEmployeeDraft,notes:e.target.value})}/>
   </div>}
  </Dialog>

  <Dialog open={Boolean(attendancePeriod)} title={attendancePeriod?.status==='medical_certificate'?'Registrar atestado':'Registrar férias'} description={attendancePeriod?`${attendancePeriod.employee.fullName} · ${attendancePeriod.employee.companyName}`:undefined} loading={attendancePeriodSaving} onClose={()=>{if(!attendancePeriodSaving)setAttendancePeriod(null);}} onConfirm={()=>void saveAttendancePeriodDraft()} confirmLabel="Salvar período">
   {attendancePeriod&&<div className="hr-workspace__edit-grid">
    <Input label="Data inicial" type="date" value={attendancePeriod.startDate} onChange={e=>setAttendancePeriod({...attendancePeriod,startDate:e.target.value,endDate:attendancePeriod.status==='medical_certificate'?addDays(e.target.value,Math.max(1,Number(attendancePeriod.days)||1)-1):attendancePeriod.endDate})}/>
    {attendancePeriod.status==='medical_certificate'?<><Input label="Quantidade de dias" type="number" min="1" value={attendancePeriod.days} onChange={e=>{const days=Math.max(1,Number(e.target.value)||1);setAttendancePeriod({...attendancePeriod,days:e.target.value,endDate:addDays(attendancePeriod.startDate,days-1)});}}/><Input label="Data final" type="date" value={addDays(attendancePeriod.startDate,Math.max(1,Number(attendancePeriod.days)||1)-1)} readOnly/></>:<Input label="Data final" type="date" value={attendancePeriod.endDate} onChange={e=>setAttendancePeriod({...attendancePeriod,endDate:e.target.value})}/>} 
    <Input label="Observações" value={attendancePeriod.notes} onChange={e=>setAttendancePeriod({...attendancePeriod,notes:e.target.value})}/>
   </div>}
  </Dialog>

  <Dialog open={Boolean(editingEmployee&&employeeDraft)} title="Editar colaborador" description={editingEmployee?`${editingEmployee.fullName} · ${editingEmployee.companyName}`:undefined} loading={savingEmployee} onClose={()=>{if(!savingEmployee){setEditingEmployee(null);setEmployeeDraft(null);setEmployeeFeedback(null);}}} onConfirm={()=>void saveEmployeeEdit()} confirmLabel="Salvar alterações">
   {employeeDraft&&<div className="hr-workspace__edit-grid">
    {employeeFeedback&&<div className="hr-workspace__edit-wide"><Feedback tone="danger" title="Não foi possível salvar" message={employeeFeedback}/></div>}
    <Input label="Nome completo" value={employeeDraft.fullName} onChange={e=>setEmployeeDraft({...employeeDraft,fullName:e.target.value})}/>
    <Select label="Empresa" value={employeeDraft.companyId} options={editCompanyOptions} onChange={e=>setEmployeeDraft({...employeeDraft,companyId:e.target.value,costCenterId:''})}/>
    <Input label="Função" value={employeeDraft.jobTitle} onChange={e=>setEmployeeDraft({...employeeDraft,jobTitle:e.target.value})}/>
    <Select label="Tipo de vínculo" value={employeeDraft.employmentType} options={employmentTypeOptions} onChange={e=>setEmployeeDraft({...employeeDraft,employmentType:e.target.value as EmploymentType})}/>
    <Input label="CPF" value={employeeDraft.cpf} onChange={e=>setEmployeeDraft({...employeeDraft,cpf:e.target.value})}/>
    <Input label="Telefone" value={employeeDraft.phone} onChange={e=>setEmployeeDraft({...employeeDraft,phone:e.target.value})}/>
    <Input label="E-mail" value={employeeDraft.email} onChange={e=>setEmployeeDraft({...employeeDraft,email:e.target.value})}/>
    <Input label="PIX" value={employeeDraft.pix} onChange={e=>setEmployeeDraft({...employeeDraft,pix:e.target.value})}/>
    <Input label="Setor" value={employeeDraft.sector} onChange={e=>setEmployeeDraft({...employeeDraft,sector:e.target.value})}/>
    <Input label="Encarregado" value={employeeDraft.supervisor} onChange={e=>setEmployeeDraft({...employeeDraft,supervisor:e.target.value})}/>
    <Input label="Jornada semanal" type="number" value={employeeDraft.weeklyHours} onChange={e=>setEmployeeDraft({...employeeDraft,weeklyHours:e.target.value})}/>
    <Select label="Banco de horas" value={employeeDraft.bankHoursEnabled} options={[{value:'yes',label:'Ativo'},{value:'no',label:'Inativo'}]} onChange={e=>setEmployeeDraft({...employeeDraft,bankHoursEnabled:e.target.value})}/>
    <Input label="Salário" type="number" value={employeeDraft.baseSalary} onChange={e=>setEmployeeDraft({...employeeDraft,baseSalary:e.target.value})}/>
    <Select label="Obra / centro de custo" value={employeeDraft.costCenterId} options={editCostCenterOptions} onChange={e=>setEmployeeDraft({...employeeDraft,costCenterId:e.target.value})}/>
    <Input label="Data efetiva" type="date" value={employeeDraft.effectiveOn} onChange={e=>setEmployeeDraft({...employeeDraft,effectiveOn:e.target.value})} hint={editingEmployee&&employeeDraft.companyId!==editingEmployee.companyId?'A troca de empresa preserva o histórico anterior e cria um novo vínculo nesta data.':'Usada para alterações de salário ou obra.'}/>
    <Input label="Observações" value={employeeDraft.notes} onChange={e=>setEmployeeDraft({...employeeDraft,notes:e.target.value})}/>
   </div>}
  </Dialog>
 </section>;
}
